Update SS58 Codec documentation
rankanizer/polkadart pull request #105
Opened 2022-10-17 17:43 UTC by gabrielokura

## Description
This PR updates package ss58_codec README and example file.

## Why?
Completing first milestone. 

## How?
1. Update example.dart
2. Update README.

## Testing Plan 
Run `dart test` in ss58_codec package folder

2022-10-17 21:21 UTC, leonardocustodio commented
Would be nice to show the option to encode with a prefix that the user wants

2022-10-17 21:22 UTC, leonardocustodio requested changes
above

2022-10-17 22:25 UTC, Lohann commented on packages/ss58_codec/README.md
> +  print('Encoded address: $encodedAddress');
Where the SS58 prefix is defined?

2022-10-17 22:32 UTC, gabrielokura commented on packages/ss58_codec/README.md
> +  print('Encoded address: $encodedAddress');
Add one more example to encode custom addresses, but this one is encoding previous decoded address

2022-10-17 23:00 UTC, pastre commented on packages/ss58_codec/README.md
> +To use this package, add `ss58_codec` as a [dependency in your pubspec.yaml file](https://docs.flutter.dev/development/platform-integration/platform-channels).
Is this published to pub?
Can we publish it without creating it as a repository?

2022-10-18 11:13 UTC, leonardocustodio approved these changes

2022-10-18 11:23 UTC, gabrielokura commented on packages/ss58_codec/README.md
> +To use this package, add `ss58_codec` as a [dependency in your pubspec.yaml file](https://docs.flutter.dev/development/platform-integration/platform-channels).
Not yet. We can publish it using polkadart repository as reference

2022-10-18 11:24 UTC, gabrielokura commented on packages/ss58_codec/README.md
> +To use this package, add `ss58_codec` as a [dependency in your pubspec.yaml file](https://docs.flutter.dev/development/platform-integration/platform-channels).
After the merge, i can publish the package to pub.dev

2022-10-18 19:18 UTC, leonardocustodio approved these changes

2022-10-19 11:17 UTC, justkawal approved these changes
Just a suggestion,
Others LGTM

2022-10-19 11:17 UTC, justkawal commented on packages/ss58_codec/pubspec.yaml
> +description: Provides encoder and decoder used to parse substrate addresses.
[Suggestion]
description: Encodes and decodes substrate addresses.

2022-10-19 11:46 UTC, merged