add events, calls, type hashing, exceptions
rankanizer/polkadart pull request #114
Opened 2022-10-18 10:02 UTC by justkawal

## Any follow ups?
Please review PR: #100, before reviewing this PR.

## Description
* Adds Exceptions
* Adds Logic for type-hashing (HashNode, TypeHasher):
    - Hashes the list of types and stores their hashed `sha256` in `weak-map`.
    - Helps to do a fast-lookup quickly.
* Adds EventsRegistry logic

## Future task:
- [ ] Unit Test `TypeHashing`: #112
- [ ] Unit Test `EventRegistry`: #113

## Testing Plan 
* Unit Tests will be added in future PRs  with resolving issues:
    - #112
    - #113

2022-10-19 14:25 UTC, justkawal commented on packages/substrate_metadata/pubspec.yaml
> +      path: packages/polkadart_scale_codec
@Lohann Suggestion Committed ✅

2022-10-19 14:35 UTC, Lohann requested changes

2022-10-19 14:35 UTC, Lohann commented on packages/substrate_metadata/lib/utils/utils.dart
> +    return value != 0;
I'm not sure if a number being equal to zero can be considered empty..

2022-10-19 14:35 UTC, Lohann commented on packages/substrate_metadata/lib/types_hashing.dart
> +///
```suggestion
///
/// Computes hashes of substrate types for the purpose of equality derivation.
///
/// Substrate types form a cyclic directed graph.
/// Two types are equal when their depth-first traversal trees are equal.
/// Inline with equality, we define a type hash to be a merkel hash of it's depth-first traversal.
///
/// Note, that unlike a classic tree case we might need
/// to visit mutually recursive type nodes more than once.
///
/// Naive approach of performing a depth-first traversal for each node might not work,
/// as we typically have around 10^3 nodes in a graph. This is on a verge of being slow.
///
/// Hence, the following procedure:
/// 1. We embed Tarjan's strongly connected components algorithm in our hash computation to discover and
/// persist information about strongly connected components.
///  2. For each strongly connected component, we cache the resulting hash per entry point.
///
/// This allows us to visit non-mutually recursive types only once and makes the overall procedure
/// quadratic only on the size of a maximal strongly connected component, which practically should not be big.
///
```

2022-10-19 14:35 UTC, Lohann commented on packages/substrate_metadata/lib/types_hashing.dart
> +///Get a strong hash of substrate type, which can be used for equality derivation
```suggestion
/// Get a strong hash of substrate type, which can be used for equality derivation
```

2022-10-20 12:03 UTC, Lohann approved these changes

2022-10-20 12:45 UTC, merged