Adds mapped models for metadata
rankanizer/polkadart pull request #115
Opened 2022-10-18 13:07 UTC by justkawal

# Why big PR:
* Model Classes are calling each other and are internally tightly couple with each other.
* Its just an image of the metadata of the chain.
* Why tightly coupled: **( Metadata reuses the available types with the use of mapped keys. )**

## Any follow ups?
Please review PR: #114 , before reviewing this PR.

## Description
* This PR adds model classes for the substrate type bundles.
* Model classes is a 1-1 mapping to be filled with the decoded metadata of the chains.

## How helpful ?
* When we will decode the chain in the future PRs, then it will help us to traverse through the metadata with types available on the go without having to look for keys in `hashmaps` and then casting the types again and again.
* It helps in parsing the `ChainDescription` of the specified chain.

2022-10-18 15:28 UTC, Lohann requested changes
I see a lot of new code, but no examples on how to use it, or tests.

2022-10-18 15:28 UTC, Lohann commented on packages/substrate_metadata/lib/models/storage/storage.dart
> +///
**[optional suggestion]**
Why not split this into two files?

2022-10-18 15:28 UTC, Lohann commented on packages/substrate_metadata/lib/models/metadata/metadata_base.dart
> +  static Metadata fromVersion(Map<String, dynamic> json, int version) {
I don't see tests for this method, is this tested already?

2022-10-18 15:28 UTC, Lohann commented on packages/substrate_metadata/lib/models/version_description.model.dart
> +class VersionDescription extends SpecVersion {
Where we use it?

2022-10-18 18:17 UTC, justkawal commented on packages/substrate_metadata/lib/models/storage/storage.dart
> +///
Done ✅

2022-10-18 19:19 UTC, leonardocustodio approved these changes

2022-10-19 11:51 UTC, leonardocustodio approved these changes

2022-10-19 12:36 UTC, leonardocustodio approved these changes

2022-10-19 15:34 UTC, gabrielokura approved these changes

2022-10-20 15:19 UTC, merged