Polkadart scale codec documentation
rankanizer/polkadart pull request #120
Opened 2022-10-19 13:30 UTC by justkawal

## Description
* Adds documentation for polkadart_scale_codec

Documentation Preview can be seen at: https://github.com/rankanizer/polkadart/blob/justkawal/polkadart-scale-codec-documentation/packages/polkadart_scale_codec/README.md

2022-10-19 15:29 UTC, leonardocustodio requested changes

2022-10-19 15:29 UTC, leonardocustodio commented on packages/polkadart_scale_codec/README.md
> +### [polkadart_scale_codec](https://www.pub.dev/packages/polkadart_scale_codec) is a flutter and dart library for encoding and decoding types supported by **polkadot**.
Let's not make this text giant and bold

2022-10-19 15:29 UTC, leonardocustodio commented on packages/polkadart_scale_codec/README.md
> +  dart pub get
There are some extra spaces

2022-10-19 15:29 UTC, leonardocustodio commented on packages/polkadart_scale_codec/README.md
> +  flutter pub get
Extra spaces

2022-10-19 15:29 UTC, leonardocustodio commented on packages/polkadart_scale_codec/README.md
> +    import 'package:polkadart_scale_codec/polkadart_scale_codec.dart';
Extra spaces

2022-10-20 07:33 UTC, justkawal commented on packages/polkadart_scale_codec/README.md
> +    import 'package:polkadart_scale_codec/polkadart_scale_codec.dart';
Done ✅

2022-10-20 07:33 UTC, justkawal commented on packages/polkadart_scale_codec/README.md
> +  dart pub get
Done ✅

2022-10-20 07:33 UTC, justkawal commented on packages/polkadart_scale_codec/README.md
> +### [polkadart_scale_codec](https://www.pub.dev/packages/polkadart_scale_codec) is a flutter and dart library for encoding and decoding types supported by **polkadot**.
Done ✅

2022-10-20 07:34 UTC, justkawal commented on packages/polkadart_scale_codec/README.md
> +### [polkadart_scale_codec](https://www.pub.dev/packages/polkadart_scale_codec) is a flutter and dart library for encoding and decoding types supported by **polkadot**.
Only left the title giant and bold.

2022-10-20 12:09 UTC, Lohann requested changes
I don't see an example for `struct`

2022-10-20 12:09 UTC, Lohann commented on packages/polkadart_scale_codec/README.md
> +Struct | `_struct`
Hmm, why underscore before enum and struct?

2022-10-20 12:35 UTC, justkawal commented on packages/polkadart_scale_codec/README.md
> +Struct | `_struct`
`_enum` was used by every chain's schema.

2022-10-20 12:35 UTC, justkawal commented
> I don't see an example for `struct`

Adding example for struct.

2022-10-20 14:25 UTC, pastre approved these changes

2022-10-20 15:50 UTC, gabrielokura approved these changes

2022-10-20 15:59 UTC, merged