Metadata decoder
rankanizer/polkadart pull request #121
Opened 2022-10-19 17:10 UTC by justkawal

## Any follow ups?
Please review PR: #115, before reviewing this PR.

## Description
* Adds Metadata Decoder.
* Added `substrate_metadata` to `test.yml`. (To include tests from substrate_metadata in CI)

## Test
`dart test`

2022-10-19 22:31 UTC, leonardocustodio approved these changes

2022-10-20 14:29 UTC, pastre commented on packages/substrate_metadata/lib/metadata_decoder.dart
> +/// (Singleton)
Why is this a singleton?

2022-10-20 15:15 UTC, justkawal commented on packages/substrate_metadata/lib/metadata_decoder.dart
> +/// (Singleton)
Because then it would process all the metadata definitions again and again by calling _createScaleCodec() which is a heavy task.

So avoiding the same repetition of this task.

2022-10-23 20:19 UTC, Lohann requested changes

2022-10-23 20:19 UTC, Lohann commented on packages/substrate_metadata/lib/metadata_decoder.dart
> +  static final MetadataDecoder instance = MetadataDecoder._internal();
Singleton is an anti-pattern in modern applications and must be used only in very specific scenarios. A singleton is shared mutable state, and usually makes the app really hard to test (because all tests touch the global state).

Singleton can be replaced by `Context` objects, which instead of having a global reference, we pass then as parameters to parts of the application which needs a shared state.

2022-10-23 20:21 UTC, Lohann commented on packages/substrate_metadata/lib/metadata_decoder.dart
> +  static final MetadataDecoder instance = MetadataDecoder._internal();
https://codewithandrea.com/articles/flutter-singletons/

2022-10-25 12:14 UTC, justkawal commented on packages/substrate_metadata/lib/metadata_decoder.dart
> +  static final MetadataDecoder instance = MetadataDecoder._internal();
Resolved ✅

2022-10-25 18:06 UTC, justkawal commented on packages/substrate_metadata/lib/metadata_decoder.dart
> +  Map<String, dynamic> _decodePrivate(dynamic data) {
It is okay, Try to be little bit flexible, buddy.

2022-10-25 18:06 UTC, justkawal commented on packages/substrate_metadata/lib/metadata_decoder.dart
> +        9 <= version && version < 15, 'Invalid metadata version');
Resolved 🤣

2022-10-25 18:06 UTC, justkawal commented on packages/substrate_metadata/lib/metadata_decoder.dart
> +        magic == 0x6174656d, 'No magic number 0x6174656d at the start of data');
Resolved 🤣

2022-10-25 18:10 UTC, justkawal commented
Resolved as commented by Bruno.

2022-10-25 18:13 UTC, merged

2022-10-26 11:10 UTC, justkawal commented on packages/substrate_metadata/lib/metadata_decoder.dart
> +  static final MetadataDecoder instance = MetadataDecoder._internal();
> I've also seen people use a `Singleton+`, were objects have a shared instance and a public constructor. As long as its abstraction is done right and it is properly injected, it is safe to use. This is not the case of this class, just sharing knowledge.
> 
> Also: why do we need to share the decoder? Isn't it stateless?

Bruno sometimes, its important to run before starting to walk.