Add Metadata Converter
rankanizer/polkadart pull request #122
Opened 2022-10-19 17:52 UTC by justkawal

## Any follow ups?
Please review PR: #121, before reviewing this PR.

## Description
* Adds Metadata-V14 to Chain-Description Conversion
* Adds Metadata-Legacy  to Chain-Description Conversion
* Adds Cached Library to cache the processed outputs for faster computations.

## Testing Plan 
`dart test`

2022-10-23 20:44 UTC, Lohann requested changes

2022-10-23 20:44 UTC, Lohann commented on packages/substrate_metadata/lib/chain_description/parse_legacy.dart
> +   */
Create an issue for this and remove this commented code.
```suggestion
```

2022-10-23 20:44 UTC, Lohann commented on packages/substrate_metadata/lib/chain_description/parse_v14.dart
> +                  ) as scale_codec.Type;
It says the cast is unnecessary, so why not simply remove the type cast?

2022-10-24 10:20 UTC, pastre commented
When messing with codegen, please open a pull request with the generated code only and describe which command you ran to generate the code. Open other pull requests with your modifications later

2022-10-24 10:23 UTC, pastre commented on packages/substrate_metadata/lib/chain_description/parse_legacy.dart
> +   */
I'm fine with removing the comment when the issue is resolved

2022-10-25 12:30 UTC, justkawal commented on packages/substrate_metadata/lib/chain_description/parse_v14.dart
> +                  ) as scale_codec.Type;
Its an issue in VS-Code editor, I don't if this issue is coming in everyone's PC or not.
It throw me error if I do not type-cast.

2022-10-28 19:37 UTC, Lohann approved these changes

2022-11-03 12:24 UTC, justkawal commented
@leonardocustodio 
Can you please review it ?

2022-11-27 19:52 UTC, leonardocustodio approved these changes

2022-11-28 00:38 UTC, merged