Adds extrinsic, decode/encode
rankanizer/polkadart pull request #131
Opened 2022-10-20 08:17 UTC by justkawal

## Any follow ups?
Please review PR: #122, before reviewing this PR.

## Description
* Decode Extrinsic from **RawBlock** and result in **DecodedBlockExtrinsic**
* Encode decoded-extrinsic to produce encoded raw-block.

## Testing Plan 
* Issue #130, to track implementation of extrinsic testing.

2022-10-20 22:14 UTC, leonardocustodio requested changes

2022-10-20 22:14 UTC, leonardocustodio commented on packages/substrate_metadata/lib/chain/chain.dart
> +        decodedBlockExtrinsics.extrinsics.map((extrinsic) {
Shouldn't be decodedBlock.extrinsics? Or just decodedBlockExtrinsics? I mean why two times extrinsics?

2022-10-21 05:30 UTC, justkawal commented on packages/substrate_metadata/lib/chain/chain.dart
> +        decodedBlockExtrinsics.extrinsics.map((extrinsic) {
`decodedBlockExtrinsics` has a property `extrinsics` which contains decoded extrinsics data, we're looping through that data and then encoding it back again as was previous in `rawBlock`.

2022-10-21 05:31 UTC, justkawal commented on packages/substrate_metadata/lib/chain/chain.dart
> +    final List<dynamic> extrinsics = rawBlock.extrinsics.map((hex) {
@leonardocustodio Here we're looping the extrinsics in `rawBlock` and decoding them and then saving them inside `DecodedBlockExtrinsic`.

2022-11-27 19:52 UTC, leonardocustodio approved these changes

2022-11-28 14:39 UTC, leonardocustodio approved these changes

2022-11-28 14:51 UTC, justkawal commented
@gabrielokura @Lohann @pastre Can you please review it ?

2022-11-29 11:36 UTC, gabrielokura commented on packages/substrate_metadata/lib/chain_description/chain.dart
> +class Chain {
Why this class is duplicated?

2022-11-29 11:43 UTC, justkawal commented on packages/substrate_metadata/lib/chain_description/chain.dart
> +class Chain {
Fixed ✅, Merging issue.

2022-11-29 11:59 UTC, gabrielokura approved these changes

2022-11-29 12:00 UTC, merged