substrate_metadata documentation
rankanizer/polkadart pull request #137
Opened 2022-10-20 11:57 UTC by justkawal

## Description
* Adds readme.md file for `substrate_metadata`.
Preview: https://github.com/rankanizer/polkadart/tree/justkawal/document-substrate-metadata/packages/substrate_metadata

## Why?
To resolve issue: #135

2022-10-20 12:10 UTC, gabrielokura commented
Should we have an example folder in this package too?

2022-10-20 12:30 UTC, justkawal commented
> Should we have an example folder in this package too?

Yes, we should

2022-10-21 13:40 UTC, gabrielokura commented
> 
 #144

2022-10-21 13:41 UTC, gabrielokura commented
> > Should we have an example folder in this package too?
> 
> Yes, we should

#144

2022-10-21 23:04 UTC, gabrielokura approved these changes

2022-10-21 23:19 UTC, gabrielokura submitted a review, later dismissed

2022-10-21 23:19 UTC, gabrielokura commented on packages/substrate_metadata/README.md
> +import 'package:polkadart_scale_codec/polkadart_scale_codec.dart';
Is this right? Shouldn't be 'substrate_metadata...'?

2022-10-22 00:08 UTC, pastre commented on packages/substrate_metadata/README.md
> +  // create MetadataDecoder signleton instance
typo in singleton 
```suggestion
  // create MetadataDecoder singleton instance
```

2022-10-22 00:08 UTC, pastre commented on packages/substrate_metadata/README.md
> +  // create MetadataDecoder signleton instance
Also you can't create a singleton's instance, only get its reference
```suggestion
  // get MetadataDecoder singleton instance
```

2022-10-23 20:38 UTC, leonardocustodio requested changes

2022-10-23 20:38 UTC, leonardocustodio commented on packages/substrate_metadata/README.md
> +[substrate_metadata](https://www.pub.dev/packages/substrate_metadata) is a flutter and dart library for encoding and decoding chain **metadata**, **constants**, **extrinsic** and **events** of blocks
extrinsics in the plural

2022-10-23 20:38 UTC, leonardocustodio commented on packages/substrate_metadata/README.md
> +  substrate_metadata: 0.0.2
not sure we should use a fixed version here we will have to remember everytime to update here in that case

2022-10-24 10:32 UTC, pastre commented on packages/substrate_metadata/README.md
> +  substrate_metadata: 0.0.2
I think having it fixed is safer. We could have a CI step that updates that line and checks for a changelog

2022-10-25 18:17 UTC, justkawal commented on packages/substrate_metadata/README.md
> +  substrate_metadata: 0.0.2
I think `any` would do the work.

2022-10-25 18:17 UTC, justkawal commented on packages/substrate_metadata/README.md
> +  // create MetadataDecoder signleton instance
Done

2022-10-25 18:17 UTC, justkawal commented on packages/substrate_metadata/README.md
> +  // create MetadataDecoder signleton instance
Done

2022-10-25 18:17 UTC, justkawal commented on packages/substrate_metadata/README.md
> +import 'package:polkadart_scale_codec/polkadart_scale_codec.dart';
Done

2022-10-25 19:21 UTC, leonardocustodio approved these changes

2022-11-03 12:36 UTC, pastre approved these changes

2022-11-03 12:49 UTC, merged