Create new codec type for Compact
rankanizer/polkadart pull request #140
Opened 2022-10-20 15:46 UTC by gabrielokura

## Description
This PR adds a new codec type for encode/decode Compact integers.

## Why?
Refactoring `Codec`. 

## How?
1. Create new CodecCompact class
2. Create its tests for encoding/decoding values

## Testing Plan 
Run `dart test` in polkadart_scale_codec package folder

2022-10-20 15:58 UTC, gabrielokura commented
@pastre If you could check this out. I think your insights would be much helpful in this different approach

2022-10-20 20:19 UTC, pastre requested changes

2022-10-20 20:19 UTC, pastre commented on packages/polkadart_scale_codec/lib/src/types/codec_compact.dart
> +    var convertedValue = value is int ? value : (value as BigInt).toInt();
`(value as BigInt).toInt()` might be a bad idea, as values larger than what `int` supports will be clamped Look for an approach where you don't need to convert types, nor check for them in real time. A simple approach would be to treat everything as a bigint

2022-10-20 21:54 UTC, pastre commented
Generics is a tool that allows us to not specify types while keeping all the benefits from string typing. If we're gonna type cast and throw, it might be simpler to just keep stuff as simple as possible

2022-10-21 13:32 UTC, gabrielokura commented on packages/polkadart_scale_codec/lib/src/types/codec_compact.dart
> +    var convertedValue = value is int ? value : (value as BigInt).toInt();
Done! Changed CodecCompact to support only BigInt and let the user manipulates the result and transform to int (if wants)

2022-10-22 21:38 UTC, pastre commented on packages/polkadart_scale_codec/lib/src/types/codec_compact.dart
> +    int convertedValue = value.toInt();
Conversion to int might be clamped. Why aren't we using bigint?

2022-10-22 21:54 UTC, pastre commented on packages/polkadart_scale_codec/lib/src/types/codec_compact.dart
> +    int convertedValue = value.toInt();
If you need it to be an int, consider creating a guard clause for using  `value.isValidInt`. This will mitigate the pyramid of doom that's happening down here

2022-10-22 21:54 UTC, pastre commented on packages/polkadart_scale_codec/lib/src/types/codec_compact.dart
> +    } else if (convertedValue < calculateBigIntPow(2, 536).toInt()) {
`calculateBigIntPow(2, 536)` doesn't fit in an int (dart ints are as large as 2^53) and is getting clamped to 2^53. Really unsure if this is working

2022-10-22 21:54 UTC, pastre commented on packages/polkadart_scale_codec/test/test_types/codec_compact_test.dart
> +      final value = 0.toBigInt;
nit: BigInt has an API for 0, 1 and 2 (chicken count lol)
```suggestion
      final value = BigInt.zero;
```

2022-10-22 21:54 UTC, pastre commented on packages/polkadart_scale_codec/test/test_types/codec_compact_test.dart
> +  group('encode compact integers to hex', () {
Test cases should be:
- [X] Negative int should throw
- [X] 0  should encode on first condition
- [ ] 63 should encode on first condition
- [ ] 64 should encode on second condition
- [ ] 2^14 - 1 should encode on second condition
- [X] 2^14 should encode on third condition
- [ ] 2^30 - 1 should encode on third condition
- [X] 2^30 should encode on last condition
- [ ] 2^536 - 1 should encode on last condition
- [ ] 2^536 should throw

I'm happy with an issue to refactor

2022-10-22 21:54 UTC, pastre commented on packages/polkadart_scale_codec/test/test_types/codec_compact_test.dart
> +  group('encode compact integers to hex', () {
It's way more valuable to test the boundaries instead of a random value (like 69). If somebody was to change from 64 to 65, your tests would not fail

2023-02-17 18:23 UTC, closed without merging