Test Events
rankanizer/polkadart pull request #142
Opened 2022-10-21 13:18 UTC by justkawal

## Any follow ups?
Please review PR: #141, before reviewing this PR.

## Description
* Adds events testing

## Testing Plan 
`dart test`

2022-10-21 20:22 UTC, gabrielokura commented on packages/substrate_metadata/test/events_test.dart
> +    for (var originalEvent in rawBlocksList) {
these tests don't follow last bruno's tips.

He said we should avoid loops and must create readable tests titles

2022-10-21 20:23 UTC, justkawal commented on packages/substrate_metadata/test/events_test.dart
> +    for (var originalEvent in rawBlocksList) {
I have a call with him, and for this case scenario we're going with it by like these.

2022-10-21 20:24 UTC, justkawal commented on packages/substrate_metadata/test/events_test.dart
> +    for (var originalEvent in rawBlocksList) {
Its practically not possible, to search a sweet block which would be good enough to test. So, can't cherry pick any one.

2022-10-21 20:47 UTC, gabrielokura commented
I see we are testing events, but what is the meaning of these tests? How they protect us against bugs in decode && encode methods?

I mean, shouldn't we test these two different methods separately?

2022-10-21 20:53 UTC, justkawal commented
> I see we are testing events, but what is the meaning of these tests? How they protect us against bugs in decode && encode methods?
> 
> shouldn't we test these two different methods separately?

When you decode a value with use of the metadata definition only and then encode it back and get the same result as the original value then it confirms that the code understands the inputed value, as resulting in E2E testing....

Again, I'm not saying the code is 100% sweet and tight, but we will get it in future with `unit-tests.`

Future task: `unit-test` @gabrielokura .

2022-10-21 21:01 UTC, gabrielokura commented
> 

understood!

2022-10-21 21:01 UTC, gabrielokura commented
> > I see we are testing events, but what is the meaning of these tests? How they protect us against bugs in decode && encode methods?
> > shouldn't we test these two different methods separately?
> 
> When you decode a value with use of the metadata definition knowledge only and then encode it back and gets the same result as the original value then it confirms that the code understands the inputed value with the use of provided definitions or schema or metadata, as resulting in E2E testing....
> 
> Again, I'm not saying the code is 100% sweet and tight, but we will get it in future with `unit-tests.`
> 
> Future task: `unit-test` @gabrielokura .

understood!

2022-10-22 00:12 UTC, pastre commented on packages/substrate_metadata/test/events_test.dart
> +    for (var originalEvent in rawBlocksList) {
Please create an issue to track and refactor this

2022-10-22 00:12 UTC, pastre requested changes
Need to track bad tests

2022-10-25 18:23 UTC, justkawal commented on packages/substrate_metadata/test/events_test.dart
> +    for (var originalEvent in rawBlocksList) {
Tracked with #150.

2022-10-25 19:18 UTC, leonardocustodio approved these changes

2022-10-26 16:27 UTC, pastre approved these changes

2022-11-29 12:47 UTC, merged