Add docker to run tests easily
rankanizer/polkadart pull request #155
Opened 2022-11-05 22:42 UTC by leonardocustodio

Just run `docker compose up` in the root folder.

2022-11-07 10:51 UTC, justkawal approved these changes
LGTM

2022-11-07 11:47 UTC, gabrielokura commented
I'm getting this error when i run `docker compose up`
```
 => [ 2/12] RUN apt-get update                                                                                                                                                                                                                                                                                   7.2s
 => ERROR [ 3/12] RUN apt-get install -y curl git wget unzip libgconf-2-4 gdb libstdc++6 libglu1-mesa fonts-droid-fallback lib32stdc++6 python3                                                                                                                                                                  1.1s
------
 > [ 3/12] RUN apt-get install -y curl git wget unzip libgconf-2-4 gdb libstdc++6 libglu1-mesa fonts-droid-fallback lib32stdc++6 python3:
#0 0.343 Reading package lists...
#0 0.902 Building dependency tree...
#0 1.032 Reading state information...
#0 1.080 E: Unable to locate package lib32stdc++6
#0 1.080 E: Couldn't find any package by regex 'lib32stdc++6'
------
failed to solve: executor failed running [/bin/sh -c apt-get install -y curl git wget unzip libgconf-2-4 gdb libstdc++6 libglu1-mesa fonts-droid-fallback lib32stdc++6 python3]: exit code: 100
```

2022-11-09 12:00 UTC, justkawal requested changes
With the suggested change the issue is gone.

2022-11-09 12:00 UTC, justkawal commented on docker/Dockerfile
> +RUN apt-get install -y curl git wget unzip libgconf-2-4 gdb libstdc++6 libglu1-mesa fonts-droid-fallback lib32stdc++6 python3
```suggestion
RUN apt-get install -y curl git wget unzip libglu1-mesa
```

2022-11-10 12:53 UTC, justkawal approved these changes
LGTM

2022-11-10 20:53 UTC, Lohann approved these changes

2022-11-10 20:53 UTC, merged