Test Cases with Optimisations
rankanizer/polkadart pull request #166
Opened 2022-12-16 21:12 UTC by justkawal

## Description
- Test-Cases with manual Metadata usage:
    - `Extrinsic`
    - `Events`
    - Constants
- Bug Fixes
- Optimised by pre-checking `isPreV14` in `Chain()` Wrapper.

## Why?
As asked in the review to show an example / test-case where direct / manual usage of Metadata is demonstrated without using LegacyTypes.

## How?
- By decoding Metadata - V14, and then creating ChainDescription from it, we could use the` ChainDescription` nearly in everything without even knowing the chain-definition.
- In this way `LegacyTypes` is not needed when used `Metadata - V14`.

## Testing Plan 
`dart test`

2022-12-16 21:14 UTC, justkawal commented
@Lohann Can you review it please ?

Most of it is just parsed data for `events and extrinsics test-cases` and actual understandable code is less than `200 lines`.

2022-12-16 21:56 UTC, leonardocustodio approved these changes

2022-12-16 22:18 UTC, Lohann requested changes

2022-12-16 22:18 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/registry.dart
> +  List<Type> _fixU256Structs(List<Type> types) {
Did you created this fix? or is it from subsquid? can you put a reference why we need this fix?

2022-12-16 22:18 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/registry.dart
> +  List<Type> _fixU256Structs(List<Type> types) {
this seems a bit hack

2022-12-16 22:22 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/registry.dart
> +  List<Type> _fixU256Structs(List<Type> types) {
Alright will put a reference in code tomorrow morning:

https://github.com/subsquid/squid-sdk/blob/5ece47edd3bd8da88643cc6a735b13eea2a5eeb6/substrate/substrate-metadata/src/util.ts#L46

2022-12-17 13:05 UTC, Lohann approved these changes

2022-12-17 13:05 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/registry.dart
> +  List<Type> _fixU256Structs(List<Type> types) {
Aweosme, thanks for the clarification @justkawal !! approved

2022-12-17 13:33 UTC, merged