Change decoding bytes array
rankanizer/polkadart pull request #177
Opened 2022-12-26 08:49 UTC by justkawal

## Description
- Add different way to decode bytes buffer to return account address.

## Why?
- Resolves Issue: #176

2022-12-26 15:18 UTC, pastre requested changes

2022-12-26 15:18 UTC, pastre commented on packages/substrate_metadata/lib/utils/utils.dart
> +  }
I didn't get this function: does it convert from json or to json? It doesn't look like we get a string from this. If we get a JSON object from it (dictionary, list or type), I'd rename it to `makeJsonObject()` to avoid misunderstanding the point of this function

2022-12-26 15:18 UTC, pastre commented on packages/substrate_metadata/lib/utils/utils.dart
> +  String toHuman() {
same as above: if it returns a serialized object in form of a string, we should name it accordingly: `toJson()` is appropriate here

Another suggestion for both names is `serialize` and `deserialize`: it makes it clear that we're creating a JSON string or creating a JSON object

2022-12-26 15:18 UTC, pastre commented on packages/substrate_metadata/lib/utils/utils.dart
> +          return value;
Can't we have just `value.toString()`? Also, can't we do this in a single statement
```suggestion
          if (value is BigInt || value is scale.Some) {
            return value.toString();
          }
          return value;
```

2022-12-26 15:23 UTC, gabrielokura commented on packages/substrate_metadata/lib/utils/utils.dart
> +          return value;
Could be :
```suggestion
          return (value is BigInt || value is scale.Some) ? value.toString() : value;
```

2022-12-26 16:25 UTC, leonardocustodio commented on packages/substrate_metadata/lib/utils/utils.dart
> +  }
This function should return a JSON object as String. Pretty much like `JSON.stringify`
Imo, we should keep as `.toJson()` as this name is used in a lot of substrate libs. Like the `toHuman`.

2022-12-26 16:27 UTC, leonardocustodio commented on packages/substrate_metadata/lib/utils/utils.dart
> +  }
I believe we should be consistency with a few basic types from the Polkadot-JS API. As they are used across a lot of substrate libs. We can find the description about those in here: https://polkadot.js.org/docs/api/start/types.basics/
So I would keep it as `.toJSON` as well as the other names and if we don't have all of them probably make a few more extensions.

2022-12-26 19:57 UTC, leonardocustodio commented on packages/substrate_metadata/lib/utils/utils.dart
> +          return value;
@justkawal can you give me an example of a extrinsic with Some using this toJson? I want to check how it appears

2022-12-26 20:07 UTC, justkawal commented on packages/substrate_metadata/lib/utils/utils.dart
> +          return value;
It will appear as: `"Some(Some(123))"` or `"Some(None)"`.

Here: https://github.com/rankanizer/polkadart/blob/930fec67fa737bb234e90ffac8f8c99d70bac2c1/packages/polkadart_scale_codec/lib/src/core/option_type.dart#L51

but I'm planning to change that and remove word `Some` from the string in the upcoming PR.

2022-12-26 20:09 UTC, leonardocustodio commented on packages/substrate_metadata/lib/utils/utils.dart
> +          return value;
Ok not good. In my opinion we should make it just like an enum so it should be something like this:
`{some_key: {None: null}}}`or `{some_key: {Some: 10}}` or `{some_key: {Some: null}}`

2022-12-26 20:10 UTC, leonardocustodio commented on packages/substrate_metadata/lib/utils/utils.dart
> +          return value;
Obviously you need to check recursively as we could have Some<Some<Some<T>>>

2022-12-26 20:10 UTC, justkawal commented on packages/substrate_metadata/lib/utils/utils.dart
> +          return value;
So after removing word it would be evaluated like:

```dart
@override
String get toString() {
    if (value is _Option) {
        return (value as _Option).value.toString();
    }
    return value.toString();
}
```

So: `Some(Some(Some(123)))` would evaluated to `"123"`
So: `Some(Some(None))` would evaluated to `"None"`

2022-12-26 20:11 UTC, leonardocustodio commented on packages/substrate_metadata/lib/utils/utils.dart
> +          return value;
It is important to know if it was Some and not just the final value. For example when decoding extrinsic, I want to know the exact arg.

2022-12-26 20:22 UTC, justkawal commented on packages/substrate_metadata/lib/utils/utils.dart
> +          return value;
Like: `Some(Some(Some(123)))`  ->  `{ "some_key": { "Some": { "Some": { "Some": 123 } } } }` ?

2022-12-26 20:24 UTC, leonardocustodio commented on packages/substrate_metadata/lib/utils/utils.dart
> +          return value;
Yep, I believe that's the way to go, what do you think @Lohann

2022-12-26 20:57 UTC, pastre commented on packages/substrate_metadata/lib/utils/utils.dart
> +          return value;
It might get confused with a dictionary/custom data structure. It's fine for encoding, because you know the type you're encoding to, but you couldn't differ nested optional values from a dictionary while decoding. Most solutions solve this reserving a keyword and documenting that this conflict might happen if the user tries to use reserved keys while decoding.

2022-12-26 21:02 UTC, pastre commented on packages/substrate_metadata/lib/utils/utils.dart
> +  }
Hm, not sure I agree 😅  I think we should find the best solution for our context, which is very different from JS. But no reason to block a PR on this :)

2022-12-26 21:05 UTC, pastre commented on packages/substrate_metadata/lib/utils/utils.dart
> +          return value;
Real solution for this would be to refactor everything to make it strongly typed, but it's probably too late for that

2022-12-26 21:11 UTC, leonardocustodio commented on packages/substrate_metadata/lib/utils/utils.dart
> +          return value;
That's for the "json" output. I believe we do have the types when using default dart objects, don't we?
But yeah in theory it could be a bit confusing if using the reserved keys, for example, decoding the String Some: `{some_key: "Some"}` though it is important to know the context here, that to decode anything you need to know the metadata. So you would already know that's an enum and not a string. Because otherwise you can't even decode it.

2022-12-26 21:16 UTC, justkawal commented on packages/substrate_metadata/lib/utils/utils.dart
> +          return value;
Exactly, also I don’t see a future problem arising from it.

2022-12-26 21:18 UTC, justkawal commented on packages/substrate_metadata/lib/utils/utils.dart
> +  }
It’s common everyday term -> function name we use and understands easily.

2022-12-26 21:20 UTC, justkawal commented on packages/substrate_metadata/lib/utils/utils.dart
> +  }
If we would peek into documentation by Big Tech companies then we would find the similar documentation and function names….

Also using `toJson()` seems normal and good fit to me.

I would prefer to stick with that.

2022-12-27 05:37 UTC, justkawal commented on packages/substrate_metadata/lib/utils/utils.dart
> +          return value;
@leonardocustodio  I would also give something like: `Some.fromJson(Map<String, dynamic> map)` which would help to create the Some or None Object back.

2022-12-29 15:50 UTC, justkawal commented
@leonardocustodio Can you please approve this PR ?

2022-12-29 15:54 UTC, leonardocustodio commented
Not really, I see you took the idea of the squid approach. But there is a reason why kind is underlined in there. So we know it is not a struct. You should do the same if you are going that way.

2022-12-30 19:36 UTC, leonardocustodio approved these changes

2022-12-31 04:28 UTC, justkawal commented
@Lohann Can you please review the request ?

2023-01-02 13:40 UTC, leonardocustodio approved these changes

2023-01-02 17:45 UTC, pastre approved these changes

2023-01-02 17:45 UTC, pastre commented on packages/polkadart_scale_codec/lib/src/core/option_type.dart
> +    };
I'd avoid nesting ternaries

2023-01-02 17:45 UTC, pastre commented on packages/substrate_metadata/lib/utils/utils.dart
> +  }
Just FYI

cJSON uses encode/decode
python uses json.loads/dumps
Swift uses JSONEncoder/Decoder
serde uses from_string/to_string
Kotlin uses JSON.stringify/parse

Even native JS uses JSON.stringify/object... The only reference I know that uses `toJSON()` and `toHuman()` is that JS library

Just sharing, not asking for a change :)

2023-01-02 18:18 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/option_type.dart
> +    };
why so ?

2023-01-02 20:17 UTC, merged