Fix bit sequence
rankanizer/polkadart pull request #180
Opened 2022-12-28 19:25 UTC by justkawal

## Any follow ups?
#177 

## Description
- Fix Bit Sequence Decoding and Encoding

## Why?
#179 

## How?

## Testing Plan 
`dart test`

2022-12-28 20:12 UTC, Lohann requested changes

2022-12-28 20:12 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    }
There's a bug here when the `length > 8`, please create a test for this.

2022-12-28 20:12 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    }
Also what you are doing here is exactly what dart's [bit_array](https://pub.dev/packages/bit_array) does in a more performatic way.

https://pub.dev/documentation/bit_array/latest/bit_array/BitArray-class.html

2022-12-28 20:12 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    }
Same case here, it doesn't work when `length > 8`

2022-12-28 20:12 UTC, Lohann commented on packages/polkadart_scale_codec/test/test_types/bitvec_test.dart
> +    });
Please include more tests for with array greater than 8 bits, also use the rust code as reference.

2023-01-02 20:13 UTC, pastre requested changes

2023-01-02 20:13 UTC, pastre commented on packages/polkadart_scale_codec/test/test_types/bitvec_test.dart
> +        'When \'[1, 1, 0, 1, 1]\' is encoded then result \'0x141b\' is produced',
We need meaningful test messages for all tests

2023-01-02 20:13 UTC, pastre commented on packages/polkadart_scale_codec/test/test_types/bitvec_test.dart
> +                e.toString() == 'Invalid byte, unable to encode [-1].')));
We need a single failing condition for each expectation

2023-01-02 20:13 UTC, pastre commented on packages/polkadart_scale_codec/test/test_types/bitvec_test.dart
> +                e.toString() == 'Invalid byte, unable to encode [-1].')));
This also applies to all tests

2023-01-02 20:13 UTC, pastre commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    capacity = (capacity / 8).ceil() * 8;
`(capacity / 8).ceil()` is repeating a few times, might be a good idea to create a variable for it

2023-01-02 20:13 UTC, pastre commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +          'BitVec can have Primitives types of unsigned bit only.');
nit: improve message
```suggestion
      throw UnexpectedCaseException(
          'Expected unsigned bit with `u` prefix, but got $name which can't be decoded');
```

2023-01-02 20:13 UTC, pastre commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    return int.parse(name.substring(1));
What if `name` is `u`?

2023-01-02 20:17 UTC, justkawal commented on packages/polkadart_scale_codec/test/test_types/bitvec_test.dart
> +        'When \'[1, 1, 0, 1, 1]\' is encoded then result \'0x141b\' is produced',
@pastre Like ?

2023-01-02 20:21 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/core.dart
> +import 'package:bit_array/bit_array.dart';
Yes, it is. That's why its imported here!! I guess.... 👀

2023-01-02 20:22 UTC, justkawal commented on packages/polkadart_scale_codec/test/test_types/bitvec_test.dart
> +                e.toString() == 'Invalid byte, unable to encode [-1].')));
I want to be sure that the error is showing the correct error message and its not mistakenly edited in ay further PR. Thats why I prefer to keep the error messages check also.

2023-01-02 20:24 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    capacity = (capacity / 8).ceil() * 8;
The operation is being done on local variable and I guess there is no need to create the variable or method outside.

2023-01-02 20:33 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/registry.dart
> +        }
Done

2023-01-02 20:33 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/registry.dart
> +                  'BitVec first param must be u8, u16, u32, u64, u128 or u256');
Done

2023-01-02 20:34 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    return int.parse(name.substring(1));
Catched and checked.

2023-01-03 01:08 UTC, Lohann requested changes

2023-01-03 01:08 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    return bits;
The logic here can be simplified as following:

```dart
// get compacted length for filling result
final int length = source.compactLength();

// get the encoded bytes from the source
final Uint8List bytes = source.bytes((capacity / 8).ceil());

// Make bytes.length multiple of 4
final int extraZeros = (4 - (bytes.length % 4)) % 4;
for (var i = 0; i < extraZeros; i++) {
   bytes.insert(0, 0);
}

// Convert Uint8List to BitArray
final bits = BitArray.fromUint8List(bytes);

return bits;
```

Obs: it only works for `LSB`, for `MSB` more code and conversion is needed.

2023-01-03 01:08 UTC, Lohann commented on packages/polkadart_scale_codec/test/test_types/bitvec_u32_test.dart
> +    });
Also create a test with non-zero array, this is a good one to test because is assymetric:
```
[1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1]
```

2023-01-03 05:37 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    return int.parse(name.substring(1));
Seems a good one 💯. Nice, Thanks, Done

2023-01-03 05:40 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    }
Done ✅

2023-01-03 05:44 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    return bits;
An issue to track `MSB` is already created: #181

2023-01-05 12:34 UTC, pastre commented on packages/polkadart_scale_codec/test/test_types/bitvec_test.dart
> +                e.toString() == 'Invalid byte, unable to encode [-1].')));
I agree that we should keep both checks, but I think it's important that we're clear on the error message that we display in our framework. We want developers to be sure of what's going wrong, therefore we need to be specific and as detailed as possible when something fails 
```suggestion
            throwsA(predicate((e) {
                expect(e, isA<UnexpectedCaseException>());
                expect(e.toString(), 'Invalid byte, unable to encode [-1].');
            }
```

In the above suggestion, it's clear why our test fails

2023-01-05 12:37 UTC, pastre commented on packages/polkadart_scale_codec/test/test_types/bitvec_test.dart
> +        'When \'[1, 1, 0, 1, 1]\' is encoded then result \'0x141b\' is produced',
Why are you testing that input? What functionality that test protects? Why is that output produced?
I can't extract meaning out of your current description

2023-01-05 12:42 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    return int.parse(name.substring(1));
Did you push the changes?  I don't see the refactor

2023-01-05 12:46 UTC, pastre commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +  }
@justkawal this is what I mean by create a new variable - also doing some clean up
```suggestion
    final int capacity = max(bits.length, _getBitSequenceCapacity(def.bitStoreType));
    final int byteCapacity =  (capacity / 8).ceil()
    final bitCapacity = byteCapacity * 8;
    final bitArray = BitArray(bitCapacity);

    encoder.compact(bits.length);

    for (var i = 0; i < bits.length; i++) {
      if(i > 1 || i < 0) { continue; } // Not sure if this is necessary
      bitArray[i] = i.isOdd;
    }
    encoder.bytes(bitArray.byteBuffer.asUint8List(0, byteCapacity).toList());
  }
```

2023-01-05 12:46 UTC, pastre commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    capacity = (capacity / 8).ceil() * 8;
Added another more specific comment

2023-01-05 12:53 UTC, pastre commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    return int.parse(name.substring(1));
Nice error message!

2023-01-05 12:53 UTC, pastre commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    }
I think it's weird to have an empty string when we actually got `'u'`. `name` should provide context for the user on what's wrong
```suggestion
          'Expected unsigned bit with valid bitSize, but got $name which can\'t be decoded.');
    }
```

2023-02-17 18:23 UTC, closed without merging