Era resolution #178
rankanizer/polkadart pull request #184
Opened 2023-01-02 13:35 UTC by justkawal

## Any follow ups?
#180 

## Description
- A temporary fix to get `{"period": value, "phase": value}`.
- A issue is made to handle it in generic way: #183 
- Also added to handle `None` aka (`NoneOption`).

## Why?
#178 

## How?
- Done by manually extracting the era when making ChainDescription Types.

2023-01-02 13:38 UTC, leonardocustodio commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +      // TODO: Resolve issue: #183 - Extrinsic Era
Should we remove this?

2023-01-02 13:38 UTC, leonardocustodio commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +      // TODO: Resolve issue: #183 - Extrinsic Era
Should we remove this?

2023-01-02 13:39 UTC, leonardocustodio commented on packages/polkadart_scale_codec/lib/src/core/types.dart
> +  /// TODO: Issue: #183 : Remove this quick-fix once Extrinsic Era is implemented in Generic Way
Should we remove this?

2023-01-02 13:40 UTC, leonardocustodio approved these changes

2023-01-03 01:10 UTC, Lohann requested changes
I'm missing unit tests for this new introduced code, please at least test the `Primitive.ExtrinsicEra`

2023-01-03 01:11 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/types.dart
> +  ExtrinsicEra,
I don't like this hack solution, big chances of we miss this out here, why we need a quick fix for this?

2023-01-04 14:19 UTC, leonardocustodio commented on packages/polkadart_scale_codec/lib/src/core/types.dart
> +  ExtrinsicEra,
We kind of need this for testing ;)
Having tests to ensure it works and that when we refactor everything is correct should be good for us.

2023-02-25 08:18 UTC, closed without merging