Justkawal/complete new approach
rankanizer/polkadart pull request #186
Opened 2023-01-05 12:03 UTC by justkawal

#Resolves Issue:
- #185 

## Description
- A complete new configurable re-design
- Easy to add functionality.
- Well documented

## Why?
- More clean approach
- Less boilerplate code
- Short, clear and concised

## How?
- By isolating the decode and encode functionality inside the basic type classes.
- Lesser intermediate cyclic conversion of types: `forth and back`.

## Testing Plan
- Unit Test cases.
- Separate testing of single units
- Command:  `dart test`

2023-01-05 12:48 UTC, Lohann requested changes

2023-01-05 12:48 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/type_registry.dart
> +              case 'BTreeMap':
This case will never the be catch, because you do `.toLowerCase()` so is impossible to get `BTreeMap`.

Also I don't think we should do a lowercase here, because struct names are case sensitive, `BTreeMap` and `BTreemap` are considered different structs.

2023-01-05 12:48 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/type_registry.dart
> +              case 'BTreeMap':
Also this is bug, as such must have a unit tests covering this case, it should be catch by unit tests.

2023-01-05 12:48 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/type_registry.dart
> +              RegExp(r'^([^<]*)<(.+)>$').allMatches(value as String).toList();
What that REGEX actually try to find? can you document it please? also I think this should be moved to a separated method and properly tested.

2023-01-05 12:52 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/codec_types/bool_codec.dart
> +class BoolCodec extends Codec<bool> {
Please create a test specifically for this struct

2023-01-05 12:53 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/codec_interface.dart
> +  dynamic encode(T value);
We must avoid using `dynamic` type, instead we must use strict types.

2023-01-05 13:01 UTC, Lohann commented on packages/substrate_metadata/test/dummy_test.dart
> +  });
...

2023-01-05 15:02 UTC, justkawal commented on packages/substrate_metadata/test/dummy_test.dart
> +  });
because when the workflow will run dart test in every directory then it will crash the Github Actions

2023-01-05 21:06 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/type_registry.dart
> +              case 'BTreeMap':
Resolved ✅

2023-01-06 12:30 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/type_registry.dart
> +              RegExp(r'^([^<]*)<(.+)>$').allMatches(value as String).toList();
Done ✅
Added test-cases
Explained some few things on comment when accessing match[2] when groupCount is just 2.

2023-01-06 12:32 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/codec_types/bool_codec.dart
> +class BoolCodec extends Codec<bool> {
Test Cases already present:
- With single direct type call.
- With Custom User defined structure of json.

2023-01-06 12:32 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/codec_interface.dart
> +  dynamic encode(T value);
Done removed usage of dynamic and change it to generic `<T>`

2023-01-08 15:29 UTC, pastre requested changes

2023-01-08 15:29 UTC, pastre commented on packages/polkadart_scale_codec/test/type_registry_test.dart
> +    test('When registry is created then it should have length 1', () {
Why should it have lenght 1?

2023-01-08 15:29 UTC, pastre commented on packages/polkadart_scale_codec/test/type_registry_test.dart
> +    test('When map of codecs is added to registry then it should have length 2',
why?

2023-01-08 15:29 UTC, pastre commented on packages/polkadart_scale_codec/test/utils/extensions_test.dart
> +    test('When getter first is called on \'Hello\' then \'H\' is returned', () {
```suggestion
    test('first should return first character', () {
```

2023-01-08 15:29 UTC, pastre commented on packages/polkadart_scale_codec/test/utils/extensions_test.dart
> +    test('When getter last is called on \'Hello\' then \'o\' is returned', () {
```suggestion
    test('last is should return last character', () {
```

2023-01-08 15:29 UTC, pastre commented on packages/polkadart_scale_codec/test/utils/extensions_test.dart
> +        'When getter first is called on \'\' then UnexpectedCaseException is thrown',
```suggestion
        'given an empty string when getting first character it should throw',
```

2023-01-08 15:29 UTC, pastre commented on packages/polkadart_scale_codec/test/utils/extensions_test.dart
> +        'When getter last is called on \'\' then UnexpectedCaseException is thrown',
```suggestion
        'given an empty string when getting last character it should throw',
```

2023-01-08 15:29 UTC, pastre commented on packages/polkadart_scale_codec/test/utils/hex_test.dart
> +  group('Hex Encode Test: ', () {
When unit testing this, you shouldnt test values. The way you did it, you're using (and trusting) dart's `HexCodec`, so you only need to test if you're calling `hex.encode()`. Testing values is overall a bad idea in this case bc we're testing functionality that we don't maintain instead of testing the integration between components

2023-01-08 15:29 UTC, pastre commented on packages/polkadart_scale_codec/test/utils/hex_test.dart
> +  group('Hex Invalid Input Test: ', () {
Test for `assertionCheck`?

2023-01-08 15:29 UTC, pastre commented on packages/substrate_metadata/lib/substrate_metadata.dart
> +class Aweosme {}
?

2023-01-08 15:29 UTC, pastre commented on packages/polkadart_scale_codec/test/codec/bool_test.dart
> +  group('Test bool Decode', () {
This is not testing bool decode. It's testing that:

1. TypeRegistry.createRegistry() adds bool to its registry by default (which means bool is in the default array)
2. Codec initializes with registry
3. Codec.createTypeCodec converts the type
4. Codec.createTypeCodec finds a matching type name
5. Codec.createTypeCodec properly creates metadata and sets typeString of the new codec
6. BoolCodec decodes properly

In your test, you're only asserting for number 6, which is the only thing actually being covered. This test  will accuse more coverage then it actually covers
This test will fail if any change impacts numbers 1-5, causing it to be flaky

Please test `BoolCodec` directly

2023-01-08 15:29 UTC, pastre commented on packages/polkadart_scale_codec/lib/src/codec_types/bool_codec.dart
> +
Why is this depending on the registry? Also, it shouldn't be optional

2023-01-24 19:38 UTC, Lohann requested changes

2023-01-24 19:38 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/codec_types/bool_codec.dart
> +  final Source? source;
I really don't like this `Source` being here, I think this must be provided as parameter, not stored in the Codec.
I don't see any advantage on storing the source together in the Codec.

2023-01-24 19:38 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/codec_types/bool_codec.dart
> +  }
Simply call `source.byte()` method here:
```dart
  bool decode() {
    final byte = (source ?? data).byte();
    return byte > 0;
  }
```

2023-01-24 19:38 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/codec_types/bool_codec.dart
> +  }
Nop.. we should not use hex strings for encoding, this is very inefficient.

2023-01-24 19:38 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/codec_interface.dart
> +}
Where we use this? why not use Codec type?

2023-01-24 20:10 UTC, Lohann requested changes

2023-01-24 20:10 UTC, Lohann commented on packages/polkadart_scale_codec/test/codec/u8_test.dart
> +    });
I don't think the must provide the `input` when creating the codec, the codec and the input must be decoupled.
```dart
    test('When highest value 0xff is decoded then it returns 255', () {
      final codec = Codec(registry: registry).createTypeCodec('u8');
      final u8Value = codec.decode(input: Input('0xff'));
      expect(u8Value, equals(255));
    });
```

The input should not be stored in the codec

2023-01-24 20:10 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/type_registry.dart
> +  static const _defaultCodecTypes = <String>['Bool', 'U8'];
? where we this, and why those are the defaultCodecTypes? what basic codec names means?

2023-01-24 20:10 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/type_registry.dart
> +  static void addCustomCodec(
I agree, this function is really big and complex, and requires more testing.

2023-01-24 20:10 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/codec_interface.dart
> +mixin CodecInterface<T> {
I still don't understand where and why we need this interface

2023-01-24 20:10 UTC, Lohann commented on packages/substrate_metadata/test/dummy_test.dart
> +}
Why we need this dummy test? can't we simply remove the this folder completly?

2023-01-24 20:10 UTC, Lohann commented on packages/substrate_metadata/lib/substrate_metadata.dart
> +class Aweosme {}
?

2023-02-17 20:18 UTC, Lohann requested changes

2023-02-17 20:18 UTC, Lohann commented on packages/polkadart_scale_codec/lib/primitives/h256.dart
> +  static final H256Codec instance = H256Codec._();
Why not simply:
```dart
final H256Codec = ArrayCodec(U8Codec.instance, 32);
```
lets avoid create unnecessary primitive types.

2023-02-17 20:18 UTC, Lohann commented on packages/polkadart_scale_codec/lib/primitives/option.dart
> +class OptionCodec with Codec<OptionType> {
This seems a bit overengineered, why not simply this:
```dart
class OptionCodec<E> with Codec<E?> {
  final Codec<E> subtypeCodec;

  const OptionCodec(this.subtypeCodec);

  @override
  void encodeTo(E? maybeValue, Output dest) {
    if (maybeValue == null) {
      dest.pushByte(0);
    } else {
      dest.pushByte(1);
      subtypeCodec.encodeTo(maybeValue, dest);
    }
  }

  @override
  E? decode(Input input) {
    if (input.read() == 0) {
      return null;
    }
    return subtypeCodec.decode(input);
  }

  @override
  int sizeHint(E? maybeValue) {
    if (maybeValue == null) {
      return 1;
    }
    return 1 + subtypeCodec.sizeHint(maybeValue);
  }
}
```

2023-02-17 20:18 UTC, Lohann commented on packages/polkadart_scale_codec/lib/primitives/result.dart
> +class ResultCodec<T> with Codec<Map<String, T>> {
Do we really need a Result codec? can't we simply use an variant?
```dart
VariantCodec({
  'Ok': ObjOk.instance,
  'Err': ObjErr.insntace,
});
```

2023-02-17 20:18 UTC, Lohann commented on packages/polkadart_scale_codec/lib/primitives/struct.dart
> +class StructCodec with Codec<LinkedHashMap<String, dynamic>> {
Lets use the same name as `scale-info`, instead of `Struct` lets call it `CompositeCodec`:
https://github.com/paritytech/scale-info/blob/v2.3.1/src/ty/mod.rs#L276-L278

2023-02-17 20:18 UTC, Lohann commented on packages/polkadart_scale_codec/lib/primitives/bytes.dart
> +  static final BytesCodec instance = BytesCodec._();
We don't need this type too, we can simply use:
```dart
SequenceCodec(U8Codec.instance)
```

Is a bad practice having two ways for doing the same thing.

2023-02-17 20:18 UTC, Lohann commented on packages/polkadart_scale_codec/lib/primitives/enum.dart
> +class SimpleEnumCodec<A> with Codec<A> {
We can simplify this code, instead of two codec `SimpleEnumCodec ` and `ComplexEnumCodec` which increase complexity, lets have just one `VariantCodec`, which accepts null as codec:
```dart
VariantCodec({
  'A': null,
  'B': U8Codec.instance,
  'C': PointCodec.instance,
})
```
We can have a specialized constructor for simple enum:
```dart
VariantCodec.fromValues(['VariantA', 'VariantB', 'VariantC'])
// same as
VariantCodec({
  'VariantA': null,
  'VariantB': null,
  'VariantC': null,
})
```

2023-02-17 20:57 UTC, Lohann commented on packages/polkadart_scale_codec/lib/primitives/option.dart
> +class OptionCodec with Codec<OptionType> {
Btw, for dynamic, an `Option` is simply an enum:
```dart
VariantCodec({
  'None': null,
  'Some': ValueCodec.instance,
})
```

2023-02-26 15:23 UTC, Lohann commented on packages/polkadart_scale_codec/lib/primitives/str.dart
> +}
Test are missing for this one, is also wrong, it MUST convert the string to utf-8:

```dart
import '../scale_codec.dart' show Codec, Input, Output;
import './compact.dart' show CompactCodec;
import './u8.dart' show U8Codec;
import 'dart:convert' show utf8;

class StrCodec with Codec<String> {
  const StrCodec._();

  static const StrCodec codec = StrCodec._();

  @override
  void encodeTo(String str, Output dest) {
    final utf8str = utf8.encode(str);
    CompactCodec.codec.encodeTo(utf8str.length, dest);
    for (final charCode in utf8str) {
      U8Codec.codec.encodeTo(charCode, dest);
    }
  }

  @override
  String decode(Input input) {
    final size = CompactCodec.codec.decode(input).toInt();
    final bytes = input.readBytes(size).toList();
    return utf8.decode(bytes);
  }

  @override
  int sizeHint(String str) {
    var size = CompactCodec.codec.sizeHint(str.length);
    size += utf8.encode(str).length;
    return size;
  }
}
```

2023-02-26 15:23 UTC, Lohann commented on packages/polkadart_scale_codec/lib/primitives/null_codec.dart
> +}
Instead of dynamic, use void, so the compiler knows the element have size equals to zero:
- https://medium.com/flutter-community/the-curious-case-of-void-in-dart-f0535705e529
```dart
import '../scale_codec.dart' show Codec, Input, Output;

class NullCodec with Codec<void> {
  const NullCodec._();

  static const EmptyCodec codec = EmptyCodec._();

  @override
  void encodeTo(void element, Output output) {
    return;
  }

  @override
  void decode(Input input) {}

  @override
  int sizeHint(void element) {
    return 0;
  }
}
```

2023-02-26 15:23 UTC, Lohann commented on packages/polkadart_scale_codec/lib/primitives/option.dart
> +  const OptionType(this.kind, [this.value]);
There's a bug here if `OptionType<T?>`, to fix that use this:
```

2023-02-26 15:28 UTC, Lohann commented on packages/substrate_metadata/test/dummy_test.dart
> +}
Please remove the dummy test

2023-03-02 14:42 UTC, Lohann requested changes

2023-03-02 14:42 UTC, Lohann commented on packages/polkadart_scale_codec/lib/primitives/compact.dart
> +        ..pushByte((value.toInt() >> 22).toUnsigned(8));
The value is already of type int here
```dart
      output.pushByte(value << 2);
    } else if (value < 16384) {
      output
        ..pushByte((value & 0x3F) << 2 | 1)
        ..pushByte((value >> 6).toUnsigned(8));
    } else if (value < 1073741824) {
      output
        ..pushByte((value & 0x3F) << 2 | 2)
        ..pushByte((value >> 6).toUnsigned(8))
        ..pushByte((value >> 14).toUnsigned(8))
        ..pushByte((value >> 22).toUnsigned(8));
```

2023-03-02 14:42 UTC, Lohann commented on packages/polkadart_scale_codec/lib/primitives/compact.dart
> +        output.pushByte(value.toUnsigned(8).toInt());
```suggestion
        output.pushByte(value.toUnsigned(8));
```

2023-03-02 14:42 UTC, Lohann commented on packages/polkadart_scale_codec/lib/primitives/enum.dart
> +  final List<A?> list;
This should be an Map, because even simple enums can have sparse indexes, ex:

```rust
enum SomeEnum {
  #[index(0)]
  Value1,
  #[index(10)]
  Value2,
  #[index(30)]
  Value3,
}
```

2023-03-02 14:42 UTC, Lohann commented on packages/polkadart_scale_codec/lib/primitives/enum.dart
> +  final Map<String, Codec<V?>?> map;
Same case here, where do you store the enum index?

2023-03-02 14:42 UTC, Lohann commented on packages/polkadart_scale_codec/lib/primitives/enum.dart
> +    codec?.encodeTo(value.value, output);
Unnecessary line break.
```suggestion
    output.pushByte(index);
    final codec = map[value.key];
    codec?.encodeTo(value.value, output);
```

2023-03-02 14:42 UTC, Lohann commented on packages/polkadart_scale_codec/lib/primitives/enum.dart
> +    return MapEntry(key, codec?.decode(input));
```suggestion
    final key = map.keys.elementAt(index);
    final codec = map[key];
    return MapEntry(key, codec?.decode(input));
```

2023-03-02 14:42 UTC, Lohann commented on packages/polkadart_scale_codec/test/direct_tests/array_test.dart
> +    });
Nice ❤️

2023-03-02 14:42 UTC, Lohann commented on packages/polkadart_scale_codec/test/direct_tests/i16_test.dart
> +  group('I16 Decode Test:', () {
We also need tests for `OutOfBounds` errors

2023-03-02 14:42 UTC, Lohann commented on packages/polkadart_scale_codec/test/direct_tests/i256_test.dart
> +  group('I256 Decode Test:', () {
We also need tests for `OutOfBounds` errors

2023-03-02 14:42 UTC, Lohann commented on packages/polkadart_scale_codec/test/direct_tests/i128_test.dart
> +  group('I128 Decode Test:', () {
We also need tests for `OutOfBounds` errors

2023-03-02 14:42 UTC, Lohann commented on packages/polkadart_scale_codec/test/direct_tests/option_test.dart
> +    });
Nice

2023-03-02 14:42 UTC, Lohann commented on packages/polkadart_scale_codec/test/direct_tests/simple_enum_test.dart
> +    });
We need tests for sparse indexes, I think in this case we can do this:
```dart
SimpleEnumCodec.sparse({
  'a': 0,
  'b': 10,
  'c': 20,
});
```

2023-03-02 14:45 UTC, Lohann commented on packages/polkadart_scale_codec/test/direct_tests/simple_enum_test.dart
> +    });
Or the inverse (so we guarantee the index is unique):
```dart
SimpleEnumCodec.sparse({
  0: 'a',
  10: 'b'
  20: 'c',
});
```

2023-03-02 14:52 UTC, Lohann commented on packages/polkadart_scale_codec/lib/io/byte_input.dart
> +    return _buffer[offset++];
Wondering where the offset is stored

2023-03-02 14:52 UTC, Lohann commented on packages/polkadart_scale_codec/lib/io/hex_input.dart
> +    return _buffer[offset++];
Same case here, where this offset is stored?

2023-03-02 14:58 UTC, Lohann commented on packages/polkadart_scale_codec/lib/primitives/option.dart
> +  final bool _isSome; // Workaround for Option<int?>.some(null)
```suggestion
class Option<T> extends Equatable {
  final T value;
  final bool _isSome; // Workaround for Option<int?>.some(null)
```

2023-03-06 21:27 UTC, closed without merging