Feature/polkadart scale codec
rankanizer/polkadart pull request #22
Opened 2022-09-06 09:51 UTC by justkawal

## Core Code
- [ ] Scale Codec Compact Functionality
- [ ] Scale Codec Encode / Decode
- [ ] Scale Codec Type Conversion

## Testing:
- [ ] Testing Compact Functionality
- [ ] Testing Encode / Decode
- [ ] Testing Scale Codec Type Conversion

## Task in progress:
- To test scale codec type conversion with Para-chains data, we need to be able to parse metadata. Thus coding part of metadata parsing functionality inside **test-chain** folder.

2022-10-01 00:06 UTC, pastre requested changes
6 files to go still. Will wait on current changes

2022-10-01 00:06 UTC, pastre commented on packages/polkadart_scale_codec/test/test_chain/shiden_test.dart
> +  group('Chain: shiden', () {
Instead of having multiple groups, can't we have a single group for `testExtrinsicsScaleEncodingDecoding`, a single group for `testConstantsScaleEncodingDecoding` and a single group for `testEventsScaleEncodingDecoding`? We can add test cases for each chain there

2022-10-01 00:06 UTC, pastre commented on packages/polkadart_scale_codec/test/test_types/bitvec_test.dart
> +    for (var vec in [1, 2, 3]) {
Please avoid for loops

2022-10-01 00:06 UTC, pastre commented on packages/polkadart_scale_codec/test/test_types/bitvec_test.dart
> +      test('$vec', () {
Please improve the test's description

2022-10-01 00:06 UTC, pastre commented on packages/polkadart_scale_codec/test/test_types/bitvec_test.dart
> +    for (var vec in [1, 2, 3]) {
Please improve the variables's name
```suggestion
    for (var expectedValue in [1, 2, 3]) {
```

2022-10-01 00:06 UTC, pastre commented on packages/polkadart_scale_codec/test/test_types/bitvec_test.dart
> +        var encoded = codec.encodeToHex(registry.use('BitVec<u8>'), [vec]);
These should be separate unit tests: what if both encode `encodeToHex` and `decodeBinary` have the same error and encode/decode to the same expected value?

2022-10-01 11:06 UTC, justkawal commented on packages/polkadart_scale_codec/create_coverage.sh
> +genhtml -o ./coverage/report ./coverage/lcov.info
This will be done in ReadMe.md in a new PR.

2022-10-01 11:07 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +  Uint8List encodeToBinary(int type, dynamic val) {
Yes it returns and array of bytes i.e. (Buffer (as said in common terms)).
It's binary data and Uint8List represents as Buffer in dart.

2022-10-01 11:08 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    var val = decode(type, src);
No we don't need to handle it here.
It throws only when it is desired because we can't cover that particular case in switch-case.

2022-10-01 11:23 UTC, justkawal commented on packages/polkadart_scale_codec/test/test_types/bitvec_test.dart
> +        var encoded = codec.encodeToHex(registry.use('BitVec<u8>'), [vec]);
Done

2022-10-01 11:24 UTC, justkawal commented on packages/polkadart_scale_codec/test/test_types/bitvec_test.dart
> +    for (var vec in [1, 2, 3]) {
Removed as separate tests

2022-10-01 11:24 UTC, justkawal commented on packages/polkadart_scale_codec/test/test_types/bitvec_test.dart
> +      test('$vec', () {
Done

2022-10-01 11:25 UTC, justkawal commented on packages/polkadart_scale_codec/test/test_types/bitvec_test.dart
> +    for (var vec in [1, 2, 3]) {
Removed

2022-10-01 11:31 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +  dynamic decodeBinary(int type, dynamic data) {
I don't think so we could predict the decoded result, because it totally depends on the val which use passes with the type int fetched from registry.use,

For different encoded data we could get different result like: (int?, String?, bool?, List<T?>?, HashMap<K?, V?>?);

where T is any type.
and <K, V> denotes Key Value pair of any type.
? -> denotes the type returned could hold null too depending on encoded data.

2022-10-01 12:17 UTC, justkawal commented on packages/polkadart_scale_codec/test/test_chain/src/chain.dart
> +abstract class Chain implements _$Chain {
User is not going to use this class, So it doesn't effect the developers using this package.

Also the integrity of this package stays put untill and unless we accept a PR changing this class which might be questionable.

2022-10-01 12:36 UTC, justkawal commented on packages/polkadart_scale_codec/test/test_chain/shiden_test.dart
> +  group('Chain: shiden', () {
I tried that by putting all the test cases under one file named as: `chains_test.dart`, but it ended up being the terminal killed by kernel due to lot of load all together.

So, with separate void main() in separate files it takes less than 3 mins to run the test cases on M1, while the test cases on same file takes around 20 mins on the same system considering the system just restarted in both cases.

2022-10-01 12:47 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/util/extensions.dart
> +extension IntExtension on int {
Done

2022-10-01 12:47 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/util/extensions.dart
> +  BigInt get bigInt {
Done

2022-10-01 12:48 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/util/extensions.dart
> +  BigInt get bigInt {
done

2022-10-01 12:48 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/util/extensions.dart
> +extension StringExtension on String {
done

2022-10-01 12:51 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/util/extensions.dart
> +    return BigInt.parse(this);
Done

2022-10-01 12:53 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/types_codec.dart
> +part of polkadart_scale_codec_core;
These are covered while testing the chains.

2022-10-01 12:59 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/sink.dart
> +abstract class Sink {
I don't think so but changed for good to `ScaleCodecSink`.

2022-10-01 13:04 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    assertNotNull(val is List && val.length == def.len);
Yes they will fail in production as it's not the assert provided by dart.

It's manually written by us which explicitly throws `AssertionException` when bool value is `false`.

2022-10-01 13:14 UTC, justkawal commented on packages/polkadart_scale_codec/test/test_chain/src/chain.dart
> +abstract class Chain implements _$Chain {
The end goal is to match whether the internal functions are parsing the metadata and producing the expected result or not.

2022-10-01 13:15 UTC, pastre commented on packages/polkadart_scale_codec/test/test_chain/src/chain.dart
> +abstract class Chain implements _$Chain {
It affects the developers because a bug in it might will have consequences like:
1. Blocking the pipeline for new PRs
2. Not failing a test that should fail
3. Passing a test that should fail

This test approach is not enough to ensure our code works

2022-10-01 13:15 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +Uint8List _decodeBitSequence(Src src) {
Done

2022-10-01 13:17 UTC, pastre commented on packages/polkadart_scale_codec/lib/src/core/types_codec.dart
> +part of polkadart_scale_codec_core;
Ok. Maybe create a TODO to add unit tests, so that we can track what is missing?

2022-10-01 13:18 UTC, pastre commented on packages/polkadart_scale_codec/test/test_chain/src/chain.dart
> +abstract class Chain implements _$Chain {
If we're not testing it, we can't know that it has no bugs

2022-10-01 13:26 UTC, justkawal commented on packages/polkadart_scale_codec/test/test_chain/src/chain.dart
> +abstract class Chain implements _$Chain {
> If we're not testing it, we can't know that it has no bugs

The testing code is calling the source/core code to check for the desired matching results, if the desired matching result is not found then the test expect() fails.

It's calling substrate metadata code to get the metadata and then pass it to the polkadart_scale_codec.

We can't call substrate metadata code inside polkadart_scale_codec because substrate_metadata depends on polkadart_scale_codec so we can't make endless recusive calls to dependencies.

2022-10-01 13:27 UTC, justkawal commented on packages/polkadart_scale_codec/test/test_chain/src/chain.dart
> +abstract class Chain implements _$Chain {
![you-no-you](https://user-images.githubusercontent.com/49296873/193411739-0d3ac808-1c41-4eb9-bfd8-3072e6987baf.jpeg)

2022-10-01 13:30 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/polkadart_scale_codec_base.dart
> +    assertNotNull(data is String || data is List<int> || data is Uint8List,
Multiple Asserts Done ✅

This is a custom made assert which will fail in production if tested.

You could try to test it with a failing condition in flutter project and I'm **101%** sure it will fail.

2022-10-01 13:31 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/types.dart
> +class Field {
No he don't have it.

2022-10-01 21:31 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +  var n = src.compact();
It can't be `const` as its a result from a function.
It can be `final` for sure and will convert to it.

2022-10-01 21:41 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/types.dart
> +  final int type;
This type is int as it holds the index to the next type which will follow the decoding process for its children.

2022-10-01 21:43 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/types_codec.dart
> +part of polkadart_scale_codec_core;
I've created an issue for it to be tracked: #32

2022-10-01 21:45 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +class Codec {
I've created and issue for this to track this down. #31

2022-10-01 21:46 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/polkadart_scale_codec_base.dart
> +class Src {
Ah, Name is good, Don't worry.

I've created an issue for it, to track this easily. #33

2022-10-01 21:50 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/util/functions.dart
> +T assertNotNull<T>(T? val, [String? msg]) {
It's a function with that name only and not a native assert, as we're not calling `native assert` method inside it and explicitly throwing `Exception` by checking if the condition is `false`.

Dart doesn't stop to call methods

2022-10-01 21:50 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/util/functions.dart
> +T assertNotNull<T>(T? val, [String? msg]) {
Also now it has 2 different functions: `assertNotNull` and `assertionCheck`

2022-10-01 21:51 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/util/functions.dart
> +T assertNotNull<T>(T? val, [String? msg]) {
It's a function with that name only and not a native assert, as we're not calling `native assert` method inside it and explicitly throwing `Exception` by checking if the condition is `false`.

2022-10-01 21:55 UTC, justkawal commented on packages/polkadart_scale_codec/test/polkadart_scale_codec_test.dart
> +    expect(src.compact(), equals(val));
It's not logic here, its just `object creation`, if we couldn't create object to test it further then how could we test the code!!

2022-10-01 21:56 UTC, justkawal commented on packages/polkadart_scale_codec/test/polkadart_scale_codec_test.dart
> +    src.assertEOF();
`expect(() => src.assertEOF(), returnsNormally);`

2022-10-01 22:06 UTC, justkawal commented on packages/polkadart_scale_codec/test/bigint_test.dart
> +      for (var val in values) {
Will remove loop

2022-10-01 22:07 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/util/functions.dart
> +part of utils;
These functions are tested while testing the chains data.

2022-10-01 22:11 UTC, justkawal commented on packages/polkadart_scale_codec/test/polkadart_scale_codec_test.dart
> +  group('Test Compact: ', () {
Like ?

2022-10-02 07:35 UTC, justkawal commented on packages/polkadart_scale_codec/test/bigint_test.dart
> +  });
> This is a reason why global functions are usually a bad practice: they make it hard to unit test. `toSignedBigInt` is tightly coupled with `checkSignedBigInt`, and it's impossible to isolate it's behavior from the other function's. My suggestion is to create separate unit tests for `checkSignedBigInt`and create **integration** tests for `toSignedBigInt`. If you unit test `checkSignedBigInt` and trust that it works, it doesn't make any sense to check it again when testing `toSignedBigInt`
> 
> This is a suggested approach to test `toSignedBigInt`. It should cover all cases, together with `checkSignedBigInt` tests

**I doest make sense** when you want code coverage to reach at its max.

### It does make sense

2022-10-02 19:09 UTC, leonardocustodio requested changes

2022-10-02 19:09 UTC, leonardocustodio commented on .github/workflows/test.yml
> +    uses: rankanizer/polkadart/.github/workflows/reuseable_workflow.yml@feature/polkadart_scale_codec
Can we do this in another PR? And start using @main ?

2022-10-02 19:09 UTC, leonardocustodio commented on packages/polkadart_scale_codec/lib/src/core/polkadart_scale_codec_base.dart
> +class Src {
Try not to use abbreviations. If the meaning of this is `Source` use `Source`

2022-10-02 19:09 UTC, leonardocustodio commented on packages/polkadart_scale_codec/lib/src/core/polkadart_scale_codec_base.dart
> +    var hi = i128();
Please no abbreviations anywhere.

2022-10-02 19:09 UTC, leonardocustodio commented on packages/polkadart_scale_codec/lib/src/core/sink.dart
> +    _uncheckedU16(val);
No abbreviations

2022-10-02 19:09 UTC, leonardocustodio commented on packages/polkadart_scale_codec/lib/src/core/type_kind.dart
> +  Struct
Should this have all types? I believe there are some missing.

2022-10-02 19:17 UTC, justkawal commented on .github/workflows/test.yml
> +    uses: rankanizer/polkadart/.github/workflows/reuseable_workflow.yml@feature/polkadart_scale_codec
I did this so that this PR can run the test cases more efficiently and fastly and can process the coverage sooner as it doesn't need to run the test cases again and again separately as it was doing before.

I'll remove this for sure and make a new PR for it.

2022-10-02 19:21 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +  dynamic decodeBinary(int type, dynamic data) {
alright we'll see that in future what's the possible way of doing that.

But as far as I know that its not possible to predict before-hand to know what type of data is going to return from the encoded hexadecimal string, unless I would have already implemented it that way.

Try to understand its can be type `T`, which can have anything, literally anything.

2022-10-02 19:21 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +  dynamic decodeBinary(int type, dynamic data) {
Dart is not like Swift and Rust.

2022-10-02 19:25 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/sink.dart
> +abstract class Sink {
Refer to subsquid package for this.

2022-10-03 14:49 UTC, justkawal commented on .github/workflows/test.yml
> +    uses: rankanizer/polkadart/.github/workflows/reuseable_workflow.yml@feature/polkadart_scale_codec
I've created a new issue to track it and resolve it: #35

2022-10-03 14:52 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/polkadart_scale_codec_base.dart
> +    var hi = i128();
I've create an issue to track it: #36 and will resolve it in new PR as this PR is already too big.

2022-10-03 14:55 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/type_kind.dart
> +  Struct
If there are some types missing!!
Can you please update this issues #37 description to list them out. I'll have a look as soon as you update it.

2022-10-03 14:58 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/polkadart_scale_codec_base.dart
> +class Src {
I've create an issue to track it: https://github.com/rankanizer/polkadart/issues/36 and will resolve it in new PR as this PR is already too big.

2022-10-03 14:59 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/util/exceptions.dart
> +part of utils;
I've create an issue to track it: https://github.com/rankanizer/polkadart/issues/38 and will resolve it in new PR as this PR is already too big.

2022-10-03 15:03 UTC, justkawal commented on packages/polkadart_scale_codec/test/bigint_test.dart
> +  group('Signed BigInt: InvalidSizeException: ', () {
I've create an issue to track it: https://github.com/rankanizer/polkadart/issues/40 and will resolve it in new PR as this PR is already too big.

2022-10-03 15:05 UTC, justkawal commented on packages/polkadart_scale_codec/test/bigint_test.dart
> +        if (willPass) {
* Separately Test Happy and Bad cases in different groups. (Noted ✅)

I've create an issue to track it: https://github.com/rankanizer/polkadart/issues/40 and will resolve it in new PR as this PR is already too big.

2022-10-03 15:05 UTC, justkawal commented on packages/polkadart_scale_codec/test/bigint_test.dart
> +  group('Unsigned BigInt passes easily: ', () {
I've create an issue to track it: https://github.com/rankanizer/polkadart/issues/40 and will resolve it in new PR as this PR is already too big.

2022-10-03 15:06 UTC, justkawal commented on packages/polkadart_scale_codec/test/bigint_test.dart
> +    for (var entry in tests.entries) {
I've create an issue to track it: https://github.com/rankanizer/polkadart/issues/40 and will resolve it in new PR as this PR is already too big.

2022-10-03 15:09 UTC, justkawal commented on packages/polkadart_scale_codec/test/polkadart_scale_codec_test.dart
> +  group('Test Compact: ', () {
I've create an issue to track it: https://github.com/rankanizer/polkadart/issues/41 and will resolve it in new PR as this PR is already too big.

2022-10-03 15:09 UTC, justkawal commented on packages/polkadart_scale_codec/test/bigint_test.dart
> +            Random(Random.secure().nextInt(4294967296)).nextInt(4294967296));
I've create an issue to track it: https://github.com/rankanizer/polkadart/issues/40 and will resolve it in new PR as this PR is already too big.

2022-10-03 15:09 UTC, justkawal commented on packages/polkadart_scale_codec/test/bigint_test.dart
> +          'low': Random.secure().nextInt(4294967296),
I've create an issue to track it: https://github.com/rankanizer/polkadart/issues/40 and will resolve it in new PR as this PR is already too big.

2022-10-03 15:09 UTC, justkawal commented on packages/polkadart_scale_codec/test/bigint_test.dart
> +  });
I've create an issue to track it: https://github.com/rankanizer/polkadart/issues/40 and will resolve it in new PR as this PR is already too big.

2022-10-03 15:14 UTC, justkawal commented on packages/polkadart_scale_codec/test/polkadart_scale_codec_test.dart
> +  group('testing primitives: ', () {
I've create an issue to track it: https://github.com/rankanizer/polkadart/issues/41 and will resolve it in new PR as this PR is already too big.

2022-10-03 15:16 UTC, justkawal commented on packages/polkadart_scale_codec/test/test_chain/src/chain.dart
> +abstract class Chain implements _$Chain {
Removed as writing unit test cases for each part of scale-codec.

2022-10-03 15:32 UTC, pastre commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +  dynamic decodeBinary(int type, dynamic data) {
I understand, but most languages have such feature or libs that implement this feature.
Typescript: `JsonDecoder.object<Decodable>`
Kotlin: `JSON.parse(Decodable.serializer())`

All I'm suggesting is that the developer has the possibility to pass in the type of the data that will be decoded. That will avoid a lot of boilerplate for error handling, reduce type-casting usage and create a smoother API

2022-10-03 15:37 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +  dynamic decodeBinary(int type, dynamic data) {
Alright, after improving the current Package will do it as an improvement in future.

2022-10-06 12:51 UTC, Lohann requested changes

2022-10-06 12:51 UTC, Lohann commented on packages/polkadart_scale_codec/analysis_options.yaml
> +    non_constant_identifier_names: false
why we need those options?

2022-10-06 12:51 UTC, Lohann commented on dprint.json
> +    "block-numbers.json",
It basically disables dprint for all json files, I'm ok on disable it for all auto-generated files, but not for static ones.

2022-10-06 12:51 UTC, Lohann commented on packages/polkadart_scale_codec/create_coverage.sh
> +open ./coverage/report/index.html
I don't think this script should be in this folder, instead we must create a folder `scripts` in the root directory.

And do we need really this? is this being used by CI?

2022-10-06 12:53 UTC, justkawal commented on dprint.json
> +    "block-numbers.json",
these are the files from the chains.

2022-10-06 12:55 UTC, Lohann requested changes
When possible, please write tests for all important functions introduced in this PR, we don't need 100% coverage, but at least important functionalities and exceptions must be covered.

2022-10-06 12:55 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/sink.dart
> +  void u256(BigInt val) {
test cases missing for this function, I think this is an important one for being tested.

2022-10-06 12:55 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/sink.dart
> +  void u64(BigInt val) {
same for this, missing tests

2022-10-06 12:55 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/sink.dart
> +      write(val * 4);
No tests for when `val < 64`

2022-10-06 12:55 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/sink.dart
> +      _uncheckedU16(val >>> 14);
No tests for when `val < pow(2, 30).toInt()`

2022-10-06 12:55 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/source.dart
> +      _data = data is Uint8List ? data : Uint8List.fromList(data);
No tests for when data is not an string

2022-10-06 12:56 UTC, justkawal commented on packages/polkadart_scale_codec/create_coverage.sh
> +open ./coverage/report/index.html
It's not being used by CI.
We do not need this, but was kept for a reference if someone wants to generate Code-Coverage.

I'll put it inside the scripts folder.

2022-10-06 13:01 UTC, justkawal commented on packages/polkadart_scale_codec/analysis_options.yaml
> +    non_constant_identifier_names: false
* With `overridden_fields` there seems to be a bug with dart analyser as it says to add @override over a method which is being overridden inside the child class and after annotating it with `@override` it again suggests to remove `@override`. and hence keeps on saying to add and remove, back and forth.

* With `constant_identifier_names`:

2022-10-06 13:05 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/sink.dart
> +  void u256(BigInt val) {
I've made issues to test Sink: #42,

Do you want me to fix it here ? or make new small PR with resolving that issue ?

2022-10-06 13:55 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/source.dart
> +      throw EOFException();
TODO: #42 Implement unit tests

2022-10-06 13:57 UTC, justkawal commented on packages/polkadart_scale_codec/create_coverage.sh
> +open ./coverage/report/index.html
Removed ✅

2022-10-06 13:58 UTC, justkawal commented on dprint.json
> +    "block-numbers.json",
Changed to neglect chains folder only in dprint.json.

2022-10-06 21:05 UTC, Lohann approved these changes

2022-10-06 21:05 UTC, Lohann commented on packages/polkadart_scale_codec/test/bigint_test.dart
> +  //
```suggestion
  // Signed BigInt
  //
  // This test will pass at the boundaries of max and min values of BigInt according to bitsize
  // All the test cases will pass with [low, high] values with low and high being inclusive
```

2022-10-06 21:49 UTC, justkawal commented on packages/polkadart_scale_codec/test/bigint_test.dart
> +  //
This file is deleted in the PR: #62, sequenced to it.
This BigInt test is grouped under functions and is separated into smaller parts of files with big lines of comments removed.

Can be found in already approved PR: #62

2022-10-07 19:12 UTC, pastre approved these changes
I think the smaller issues will improve the quality of this PR. Great job @justkawal 🚀

2022-10-07 19:14 UTC, justkawal commented
> I think the smaller issues will improve the quality of this PR. Great job @justkawal 🚀

Thanks.
@leonardocustodio Waiting for your review....

2022-10-07 19:29 UTC, leonardocustodio approved these changes

2022-10-07 19:31 UTC, merged