Sparse Enums
rankanizer/polkadart pull request #261
Opened 2023-03-07 10:15 UTC by justkawal

## Description
- Use Sparse Enums

## Why?
- With using sparse constructors, it becomes easy to manage and recall indexes quicker.
- Needs space of only desired data.

## Testing Plan 
`dart test`

2023-03-07 13:28 UTC, Lohann requested changes

2023-03-07 13:28 UTC, Lohann commented on packages/polkadart_scale_codec/lib/primitives/enum.dart
> +  final Map<A, int> _keyedIndex;
Instead of two maps `Map<A, int>` and `Map<int, A>`, what do you think about using a BiMap (bidirecional map):
- https://pub.dev/documentation/quiver/latest/quiver.collection/BiMap-class.html

This is a map have this method which can you help on inverting the key and value:
https://pub.dev/documentation/quiver/latest/quiver.collection/BiMap/inverse.html

Internally it uses two maps, like you did here, but with a cleaner interface:
https://github.com/google/quiver-dart/blob/v3.2.1/lib/src/collection/bimap.dart#L50-L51

2023-03-07 13:28 UTC, Lohann commented on packages/polkadart_scale_codec/test/direct_tests/simple_enum_test.dart
> +      final codec = SimpleEnumCodec.fromList(['a', 'b', 'c']);
We also need tests for the `sparse` constructor

2023-03-07 13:28 UTC, Lohann commented on packages/polkadart_scale_codec/test/direct_tests/complex_enum_test.dart
> +        MapEntry('c', SimpleEnumCodec.fromList(['g', 'h', 'i'])),
We also need tests for the `sparse` constructor

2023-03-07 15:10 UTC, justkawal commented on packages/polkadart_scale_codec/lib/primitives/enum.dart
> +  final Map<A, int> _keyedIndex;
Nice, I'll use that for this one....

2023-03-14 19:24 UTC, justkawal commented on packages/polkadart_scale_codec/test/direct_tests/simple_enum_test.dart
> +      final codec = SimpleEnumCodec.fromList(['a', 'b', 'c']);
Adding....

2023-03-14 19:31 UTC, justkawal commented on packages/polkadart_scale_codec/test/direct_tests/complex_enum_test.dart
> +        MapEntry('c', SimpleEnumCodec.fromList(['g', 'h', 'i'])),
Added

2023-03-15 13:26 UTC, Lohann requested changes

2023-03-15 13:27 UTC, Lohann commented on packages/substrate_metadata/lib/parsers/metadata_v14_expander.dart
> +        e.value is String && e.value != 'Null')) {
I still don't understand why we need `Null` instead of using `null`

2023-03-16 17:15 UTC, justkawal commented on run_tests.sh
> +find . -maxdepth 2 -name pubspec.yaml -execdir dart test \;
Moving it to scripts folder...

2023-03-16 17:19 UTC, justkawal commented on run_dart_pub_get.sh
> +find . -maxdepth 2 -name pubspec.yaml -execdir dart pub get \;
Alright...

2023-03-21 05:39 UTC, justkawal commented on run_tests.sh
> +find . -maxdepth 2 -name pubspec.yaml -execdir dart test \;
Done

2023-03-21 05:40 UTC, justkawal commented on run_dart_pub_get.sh
> +find . -maxdepth 2 -name pubspec.yaml -execdir dart pub get \;
Done

2023-03-21 15:11 UTC, merged