Extrinsics Implementation
rankanizer/polkadart pull request #266
Opened 2023-03-13 20:39 UTC by justkawal

## Any follow ups?
#261 

## Description
- Implements `Extrinsics` Encode/Decode functionality.
- Improves Events Decoding/Encoding functionality.
- Adds Test cases for extrinsics.
- Adds specific test cases for v14 metadata.

## Testing Plan
- `./run_test.sh`

2023-03-14 18:31 UTC, Lohann requested changes
This code must work for all chains, there's a lot of specific code here for Polkadot, please include tests using Kusama, and some other parachains such as Monnbean and Acala which are the older ones.

2023-03-14 18:31 UTC, Lohann commented on packages/substrate_metadata/test/v14_tests/metadata_v14.dart
> +final metadataV14 =
Please store this fie using GIT LFS

2023-03-14 18:31 UTC, Lohann commented on packages/polkadart_scale_codec/lib/core/registry.dart
> +  }
What is is this counter?

2023-03-14 18:31 UTC, Lohann commented on packages/polkadart_scale_codec/lib/core/registry.dart
> +    return (_callsCounter[key] ?? 0) > 20;
Why this magic number?

2023-03-14 18:31 UTC, Lohann commented on packages/polkadart_scale_codec/lib/core/registry.dart
> +  }
Seems you are trying to prevent recursive calls here, that's why you need to call `_clearCounter`? there are better ways to prevent recursive calls, which is provide a Set of visited codecs as parameter to the function.

2023-03-14 19:37 UTC, justkawal commented on packages/polkadart_scale_codec/lib/core/registry.dart
> +  }
Yes.

2023-03-14 19:40 UTC, justkawal commented on packages/polkadart_scale_codec/lib/core/registry.dart
> +    return (_callsCounter[key] ?? 0) > 20;
It was the nearest and minimum number which could be used to detect stack-overflow.

2023-03-14 19:41 UTC, justkawal commented on packages/polkadart_scale_codec/lib/core/registry.dart
> +    return (_callsCounter[key] ?? 0) > 20;
Sorry for this approach, I'll create a issue to change it in further PRs.

2023-03-14 19:42 UTC, justkawal commented on packages/polkadart_scale_codec/lib/core/registry.dart
> +  }
To keep track of few called keys for the codecs, and preventing the stackOverflow

2023-03-14 19:42 UTC, justkawal commented on packages/substrate_metadata/test/v14_tests/metadata_v14.dart
> +final metadataV14 =
Alright moving file

2023-03-15 06:39 UTC, justkawal commented on packages/substrate_metadata/test/v14_tests/metadata_v14.dart
> +final metadataV14 =
Moved ✅

2023-03-15 06:40 UTC, justkawal commented on packages/polkadart_scale_codec/lib/core/registry.dart
> +    return (_callsCounter[key] ?? 0) > 20;
Issue created to track this: #275

2023-03-15 06:41 UTC, justkawal commented on packages/polkadart_scale_codec/lib/core/registry.dart
> +  }
Issue created to track this: #275

2023-03-15 06:42 UTC, justkawal commented
> This code must work for all chains, there's a lot of specific code here for Polkadot, please include tests using Kusama, and some other parachains such as Monnbean and Acala which are the older ones.

Issue created to support multiple chains: #269 

I've already started to implement a generic way to support multiple chains all at once....

2023-03-21 14:27 UTC, Lohann approved these changes

2023-03-21 15:55 UTC, merged