Feature/code generator (1/4)
rankanizer/polkadart pull request #27
Opened 2022-09-14 22:24 UTC by gabrielokura

## PR of the issue #23 
- [x] Scale Codec annotation package
- [x] Scale Codec code generator using @ScaleCodecSerializable

2022-09-15 19:43 UTC, pastre requested changes

2022-09-15 19:43 UTC, pastre commented on packages/scale_codec_serializable/lib/src/decoder_helper.dart
> +          field.startsWith('_') ? field.replaceFirst('_', '') : field;
This check is not necessary, `replaceFirst` will only replace the first character if the string begins with said character

2022-09-15 19:43 UTC, pastre commented on packages/scale_codec_serializable/lib/src/encoder_helper.dart
> +    assert(config.createDecodeMethod);
Same as above

2022-09-15 19:43 UTC, pastre commented on packages/scale_codec_serializable/lib/src/generator_helper.dart
> +    assert(_addedMembers.isEmpty);
Same as above

2022-09-15 19:43 UTC, pastre commented on packages/scale_codec_serializable/lib/src/generator_helper.dart
> +class GeneratorHelper extends HelperCore with EncoderHelper, DecodeHelper {
This is missing tests

2022-09-15 19:43 UTC, pastre commented on packages/scale_codec_serializable/lib/src/generator_helper.dart
> +          field.startsWith('_') ? field.replaceFirst('_', '') : field;
Same as above

2022-09-15 19:43 UTC, pastre commented on packages/scale_codec_serializable/lib/src/helper_core.dart
> +abstract class HelperCore {
I didn't understand: why are we creating this abstraction? Good practice is to use composition over inheritance.
Also missing tests

2022-09-15 19:43 UTC, pastre commented on packages/scale_codec_serializable/lib/src/scale_codec_serializable_generator.dart
> +    if (!element.library!.isNonNullableByDefault) {
We shouldn't force unwrap

2022-09-15 19:43 UTC, pastre commented on packages/scale_codec_serializable/lib/src/scale_codec_serializable_generator.dart
> +    if (element is! ClassElement || element is EnumElement) {
Would this crash if `element` is not of type `ClassElement`?

2022-09-15 19:43 UTC, pastre commented on packages/scale_codec_serializable/lib/src/scale_part_builder.dart
> +Builder scaleCodecPartBuilder({ScaleCodecSerializable? config}) {
Missing tests

2022-09-15 23:58 UTC, gabrielokura commented on packages/scale_codec_annotation/lib/src/scale_codec_key.dart
> +  final bool? ignore;
About the naming topic: very interesting! I found this [ref](https://dart.dev/guides/language/effective-dart/design) very helpful.

2022-09-16 00:02 UTC, gabrielokura commented on packages/scale_codec_serializable/analysis_options.yaml
> +# linter:
I don't think so. Dart analyzer is powerful and enough for now.

2022-09-16 01:29 UTC, gabrielokura commented on packages/scale_codec_serializable/lib/src/scale_codec_serializable_generator.dart
> +    if (!element.library!.isNonNullableByDefault) {
i didn't understand this point

2022-09-16 01:34 UTC, gabrielokura commented on packages/scale_codec_serializable/lib/src/scale_codec_serializable_generator.dart
> +    if (element is! ClassElement || element is EnumElement) {
Nope, will throw and the build_runner will stop showing the custom error message

2022-09-16 14:30 UTC, pastre commented on packages/scale_codec_annotation/lib/src/scale_codec_key.dart
> +  final bool? ignore;
Yep! According to the bool section, this should be `isIgnored`

2022-09-16 15:02 UTC, pastre commented on packages/scale_codec_serializable/lib/src/scale_codec_serializable_generator.dart
> +    if (!element.library!.isNonNullableByDefault) {
The `!` operator always throws when `element.library` is `null`. That's unexpected behavior (a function suddenly throwing an error) and exactly the problem that [null safety](https://dart.dev/null-safety/understanding-null-safety) aims to mitigate. You should probably safely unwrap `element.library` before accessing it's value

2022-09-26 05:28 UTC, pastre requested changes

2022-09-26 05:28 UTC, pastre commented on packages/scale_codec_serializable/test/class_generation_test.dart
> +  testAnnotatedElements(
Is this enough to ensure positive and negative behavior? (Code behaves as we expect and fails as we expect?)

2022-09-26 05:28 UTC, pastre commented on packages/scale_codec_serializable/test/encoded_fields_test.dart
> +  testAnnotatedElements(
Same as above

2022-09-26 05:28 UTC, pastre commented on packages/scale_codec_serializable/test/inputs/class_generation_test_input.dart
> +import 'package:scale_codec_annotation/scale_codec_annotation.dart';
Tests should be readable, clear and concise. Maybe notate which scenario each test is covering and using a GWT pattern to help document the test

2022-09-26 05:28 UTC, pastre commented on packages/scale_codec_serializable/test/inputs/class_generation_test_input.dart
> +    shouldCreateEncodeMethod: true, shouldCreateDecodeMethod: true)
Aren't we missing two other scenarios? `true` + `false` and `false` + `true`?

2022-09-26 05:28 UTC, pastre commented on packages/scale_codec_serializable/test/inputs/encoded_fields_test_input.dart
> +)
Also missing scenarios

2022-09-26 05:29 UTC, pastre commented
Also please consider splitting this into multiple PRs

2022-09-26 21:00 UTC, gabrielokura commented on packages/scale_codec_annotation/lib/src/scale_codec_serializable.dart
> +  }
This is veeery interesting. Thank you for the suggestion.

2022-09-26 21:55 UTC, gabrielokura commented on packages/scale_codec_serializable/example/example.dart
> +      {required this.firstName, required this.lastName, this.isYoung = false});
The `required` keyword is a way to use the same declaration style of optional parameters (firstName: "example") and still make them mandatory.

For example: 
``` Person(firstName: "example"). ```
You can only declare `firstName: "example"` when you make the parameters optionals. But if you want to ensure they will be passed you should use `required`. 
The compiler will show an error if you don't pass. 

It's nice when you have a class with N parameters, some mandatory, some optionals or nullable and want to keep the `var: value` declaration.

2022-09-26 22:00 UTC, gabrielokura commented on packages/scale_codec_serializable/example/example.dart
> +part 'example.g.dart';
Yeah, we will provide an example. I'll add this in the next PR's

2022-09-26 22:04 UTC, gabrielokura commented on packages/scale_codec_serializable/lib/src/config.dart
> +  final bool shouldCreateDecodeMethod;
Nit and imo are abbreviation of what words? :)

2022-09-27 02:24 UTC, gabrielokura commented on packages/scale_codec_serializable/lib/src/templates/all_params_template.dart
> +  String generateParamsUsage() {
`generateParamsUsage` is used in `DecodeMethodTemplate` and will be tested in PR #26

2022-09-27 03:07 UTC, gabrielokura commented on packages/scale_codec_serializable/lib/src/templates/class_template.dart
> +class ClassTemplate {
Class template are tested in `tests/inputs/class_generation_test_input.dart`

2022-09-27 03:08 UTC, gabrielokura commented on packages/scale_codec_serializable/lib/src/templates/decode_method_template.dart
> +class DecodeMethodTemplate {
Changed to extension. 

And the tests will be created in PR of #26

2022-09-27 03:09 UTC, gabrielokura commented on packages/scale_codec_serializable/lib/src/templates/encode_method_template.dart
> +    String encode() => '';
Yess, this method will be implemented in PR of #25.

2022-09-27 12:16 UTC, pastre commented on packages/scale_codec_serializable/lib/src/templates/encode_method_template.dart
> +    String encode() => '';
Cool! Might be a good idea to mark those as TODOs, so that we can use something like [TodoBot](https://github.com/apps/todobot) to open issues on remaining TODOs and keep track of those

2022-09-27 12:19 UTC, pastre commented on packages/scale_codec_serializable/lib/src/config.dart
> +  final bool shouldCreateDecodeMethod;
nit = nitpicking (picuinha, super atenção a detalhe)
imo = in my opinion

2022-09-27 12:19 UTC, pastre commented on packages/scale_codec_serializable/example/example.dart
> +      {required this.firstName, required this.lastName, this.isYoung = false});
Cool, thanks! :)

2022-09-27 12:24 UTC, pastre commented on packages/scale_codec_serializable/lib/src/templates/all_params_template.dart
> +  String generateParamsUsage() {
We should always ship our code with tests

2022-09-27 12:49 UTC, gabrielokura commented on packages/scale_codec_serializable/test/class_generation_test.dart
> +  testAnnotatedElements(
For now, our API only throw errors when the `@ScaleCodecSerializable` decorator is used in the wrong way. More possibilities will come with decode and encode methods implementation. 

But i'll add more examples and tests about the incorrect use of the decorator

2022-09-27 13:59 UTC, gabrielokura commented
> Also please consider splitting this into multiple PRs

Sure, next PR's will be smaller.

2022-10-01 14:11 UTC, pastre commented on packages/scale_codec_serializable/lib/src/utils/checks.dart
> +}
These look like they belong in an extension
```suggestion

extension ClassElementCommonCheck on ClassElement {
	void isNotAbstract() {
	  if (isAbstract) {
	    throw InvalidGenerationSourceError(
	      '[ERROR] Class ${name} cannot be abstract',
	      element: this,
	    );
	  }
	}
	
	/// Check if the class has only `one` default `const` constructor.
	///
	/// Used to avoid errors when decoding `Substrate` classes data.
	void hasOneConstConstructor() {
	  final constructorElements = constructors;
	
	  if (constructorElements.length != 1) {
	    throw InvalidGenerationSourceError(
	      '[ERROR] To many constructors in ${name} class. Class can have only one constructor',
	      element: this,
	    );
	  }
	
	  final constructor = constructorElements.first;
	
	  if (constructor.isFactory) {
	    throw InvalidGenerationSourceError(
	      '[ERROR] Class ${name} cant have one factory constructor',
	      element: this,
	    );
	  }
	}
}
```

2022-10-01 14:11 UTC, pastre commented on packages/scale_codec_serializable/test/class_generation_test.dart
> +  testAnnotatedElements(
Good APIs don't have a wrong way to be used. That looks like an issue for the future

2023-03-14 18:32 UTC, closed without merging