Change ss58-codec tests
rankanizer/polkadart pull request #30
Opened 2022-09-30 21:45 UTC by gabrielokura

# What was done
1. Change encode exception tests to check error message.
2. Change decode exception tests to check error message. 
3. Create new decode test to reach 100% test coverage.

2022-09-30 21:57 UTC, justkawal requested changes

2022-09-30 21:57 UTC, justkawal commented on packages/ss58_codec/coverage/coverage.json
> -{"type":"CodeCoverage","coverage":[{"source":"package:ss58_codec/src/exceptions.dart","script":{"type":"@Script","fixedId":true,"id":"libraries/1/scripts/package%3Ass58_codec%2Fsrc%2Fexceptions.dart"
please put coverage folder in `.gitignore` inside `ss58_codec`
Like: `coverage/`

2022-10-01 14:00 UTC, pastre requested changes
Small improvements on tests. Overall looking good!
You forgot to remove `coverage.json` and `lcov.info` from your branch xD

2022-10-01 14:00 UTC, pastre commented on packages/ss58_codec/test/ss58_codec_test.dart
>      test('data.length < 3 ', () {
I strongly recommend[ BDD Unit test naming conventions ](https://matheus.ro/2017/09/24/unit-test-naming-convention/) when naming tests. Tests should be readable and have a well defined behavior. This applies to all unit tests in this PR lol
```suggestion
    test('Should throw exception when data lenght is too small', () {
```

2022-10-01 14:00 UTC, pastre commented on packages/ss58_codec/test/ss58_codec_test.dart
>      test('invalid prefix ', () {
Using BDD's naming convention will also clean up some of your comments. They are not bad, but are usually a code smell. Your code should read itself, and if you're having to explain it using comments, usually it's not readable.
Also, use `///` only for documentation. You can use common `//` for comments
```suggestion
    test('it should throw InvalidPrefixException when an address has invalid prefix', () {
```

2022-10-01 14:00 UTC, pastre commented on packages/ss58_codec/test/ss58_codec_test.dart
> +      /// [Address] invalid because of prefix is greater than the limit
You should break this into multiple tests. Good unit tests usually fail for a single reason (that's very utopic, but nice to have). You can have ` test('it should throw InvalidPrefixException when an address has negative prefix'` and ` test('it should throw InvalidPrefixException when prefix is greater than the limit'`

2022-10-01 14:00 UTC, pastre commented on packages/ss58_codec/test/ss58_codec_test.dart
> +        );
nit: tests intrinsically have an expected value and an actual value. Notating those help with the test's readability. I'd also hard code `${invalidAddress.toString()}` to avoid changes on string conversion to affect the outcome of this test
```suggestion
         
          final expectedErrorMessage = 'Bad Length Address: ${invalidAddress.toString()}.' // TODO hardcode  ${invalidAddress.toString()}
          () => SS58Codec.encode(invalidAddress),
          throwsA(
            predicate(
              (exception) =>
                  exception is BadAddressLengthException &&
                  exception.toString() == expectedErrorMessage ,
            ),
          ),
        );
```

2022-10-01 21:26 UTC, justkawal commented on packages/ss58_codec/test/ss58_codec_test.dart
> +        );
I see, but as far as I know here its `pass by value` and `not pass by reference` so variable -> `invalidAddress` is never going to change itself or from within the encode function call.

2022-10-02 01:50 UTC, pastre commented on packages/ss58_codec/test/ss58_codec_test.dart
> +        );
I agree that it's not going to change functionality, but we're writing tests. Readability and maintainability are really really super important to ensure that we don't have any bug in our tests (bc they are the source of truth deciding whether or not our code works. Finding bugs there is terrible) and they are not a pain to maintain. To the compiler it's the same, but it's a huge difference for us. As far as the compiler knows, this one-liner is good enough lol `() => SS58Codec.encode(invalidAddress),throwsA(predicate((exception) => exception is BadAddressLengthException && exception.toString() == 'Bad Length Address: ${invalidAddress.toString()}.' ,),),);`

2022-10-02 07:27 UTC, justkawal commented on packages/ss58_codec/test/ss58_codec_test.dart
> +        );
Alright haha, will try to maintain as much readability as possible.

2022-10-02 19:01 UTC, leonardocustodio requested changes

2022-10-02 19:01 UTC, leonardocustodio commented on packages/ss58_codec/test/ss58_codec_test.dart
>      test('data.length < 3 ', () {
Highly agree with this. We should be able to know what is the goal of the tests only by their name. Even if the name is a bit big.

2022-10-03 19:19 UTC, pastre commented on packages/ss58_codec/test/ss58_codec_decode_test.dart
> +              'd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d')));
nit: avoid magic values. Consider creating named variables for `42 ` and `Uint8List.fromList(hex.decode(
              'd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d'))`. When creating variables in a test, they usually have a well defined role. Most of the times, the role is either one the five described in [this link](https://martinfowler.com/bliki/TestDouble.html). Testing doubles is the next step to upgrade your tests to the next level :)

2022-10-03 19:21 UTC, pastre commented on packages/ss58_codec/test/ss58_codec_encode_test.dart
> +    });
Consider creating multiple tests for each scenario
`test('Should encode when prefix is zero',`
`test('Should encode when prefix is 64',`
`test('Should encode when prefix is 16383',`.

Also, why those values?

2022-10-03 19:24 UTC, pastre commented on packages/ss58_codec/test/ss58_codec_encode_test.dart
> +    });
You're depending on `SS58Codec.encode`. Good unit tests have only a single reason to fail, and a flaky bug on `encode` will result on this test being flaky. Please consider hardcoding the setup:
Also: isn;t this missing an assertion?
```suggestion
    test(
        'Should encode the address and then re-decode that encoded object to match with original bytes passed',
        () {
      final String encodedAddress = SS58Codec.encode("originalAddress"); // TODO get encoded original address
      final Address decodedAddress = SS58Codec.decode(encodedAddress);
      decodedAddress.isEqual(originalAddress);
    });
```

2022-10-03 19:25 UTC, pastre commented on packages/ss58_codec/test/ss58_codec_encode_test.dart
> +      for (var len in [3, 5, 6, 7]) {
Please avoid loops in tests. you can create a single test case for each of those
Also, please consider renaming variables for clarity
```suggestion
      for (var valueStub in [3, 5, 6, 7]) {
```

2022-10-03 19:27 UTC, pastre commented on packages/ss58_codec/test/ss58_codec_encode_test.dart
> +      for (var len = 9; len <= 31; len++) {
You don't need to test all the values. Imagine if the range was wider: from 9 to 310000000. Tests would take forever to run. 
You can test : 

- 8 (lower bound - 1, should not throw)
- 9 (lower bound, should throw)
- 31 (upper bound, should throw)
- 32 (upper bound + 1, should throw) 

and that should be enough. Also, please create a different test for each of those

2022-10-03 19:28 UTC, pastre commented on packages/ss58_codec/test/ss58_codec_encode_test.dart
> +      for (var len in [34, 35]) {
Please separate into multiple tests:
- 33 is ok
- 34 breaks
- 35 breaks

2022-10-03 19:28 UTC, pastre commented on packages/ss58_codec/test/ss58_codec_encode_test.dart
> +int randomInt(int max) {
This is not being used and can be deleted

2022-10-03 19:44 UTC, gabrielokura commented on packages/ss58_codec/test/ss58_codec_encode_test.dart
> +    });
They are common values used just to test the method

2022-10-03 20:31 UTC, gabrielokura commented on packages/ss58_codec/test/ss58_codec_encode_test.dart
> +    });
We have two situations of success (not including exceptions cases) in the encode function: 
- for prefix < 64
- and for prefix > 64

So, i remove the `test('Should encode when prefix is 16383') and create tests for bytes.length that were missing.

2022-10-03 20:33 UTC, gabrielokura commented on packages/ss58_codec/test/ss58_codec_encode_test.dart
> +      for (var len in [34, 35]) {
Thanks. I see that i was taking the wrong approach for these tests. 

I will test only the edge cases of `SS58Codec.encode()`

2022-10-03 20:44 UTC, gabrielokura commented on packages/ss58_codec/test/ss58_codec_decode_test.dart
> +      decodedAddress.isEqual(expectedAddress);
It is. We've used extensions on `Address` class to make the assertion. 

But i agree this approach is not so readable.

2022-10-03 21:16 UTC, pastre approved these changes

2022-10-03 22:34 UTC, leonardocustodio approved these changes

2022-10-04 02:37 UTC, merged