Well-defined test cases for Vec
rankanizer/polkadart pull request #70
Opened 2022-10-07 09:41 UTC by justkawal

## Any follow ups?
PR: #22 already approved

## Description
* It adds test-cases for `Vec`.
* Combined Test-Cases:
    * `Vec<u8>`
    * `Vec<Vec<u8>>`
    * `Vec<u256>`
    * `Vec<i256>`
    * `Vec<(u32, u32, u16)>`
    * `Vec<(u32, Option<bool>)>`
    * `Vec<(String, bool)>`
    * `Vec<bool>`
    * `Vec<Option<bool>>` 
    * `Vec<Option<u8>>`
    * `Vec<Text>`

## How?
Testing multiple combination of test-cases helps to narrow down the breaking scenarios.

## Testing Plan 
Test the file `vec_test.dart`.

2022-10-10 13:29 UTC, gabrielokura requested changes

2022-10-10 13:29 UTC, gabrielokura commented on packages/polkadart_scale_codec/test/test_types/vec_test.dart
> +            codec.decodeBinary(registry.getIndex('Vec<u8>'), '0x08ffff');
Is this name right? Aren't we decoding a hexadecimal string?

2022-10-10 13:29 UTC, gabrielokura commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
>        assert(val == null);
this scenario isn't being reach in the tests.

2022-10-10 15:34 UTC, justkawal commented on packages/polkadart_scale_codec/test/test_types/vec_test.dart
> +            codec.decodeBinary(registry.getIndex('Vec<u8>'), '0x08ffff');
Yes, it's right if you go through the code thoroughly then you'll find out that we encodes the value to hex-decimal and then decodes it back to value.

2022-10-10 15:36 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
>        assert(val == null);
Brother, it's tuple test cases. The main motive is to test Vector and not Tuples.

2022-10-10 15:45 UTC, justkawal commented on packages/polkadart_scale_codec/test/test_types/vec_test.dart
> +        expect(expectedValue, encodedValue);
Done

2022-10-10 16:09 UTC, gabrielokura commented on packages/polkadart_scale_codec/test/test_types/vec_test.dart
> +            codec.decodeBinary(registry.getIndex('Vec<u8>'), '0x08ffff');
`decodeBinary` means we are decoding a binary value, no? If we are decoding `encoded hexa-decimal` values shouldn't the function name be `decodeHex` or `decodeFromHex`?

2022-10-10 19:05 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +      throw UnexpectedCaseException(
Done

2022-10-10 19:14 UTC, justkawal commented on packages/polkadart_scale_codec/test/test_types/vec_test.dart
> +            codec.decodeBinary(registry.getIndex('Vec<u8>'), '0x08ffff');
Changed to decodeHex. @gabrielokura 

Please consider to change this in your PR too parallely.

2022-10-10 19:22 UTC, justkawal commented on packages/polkadart_scale_codec/test/test_types/vec_test.dart
> +            codec.decodeBinary(registry.getIndex('Vec<u8>'), '0x08ffff');
Changed: 
`encodeToHex` to `encode`
`decodeBinary` to `decode`

2022-10-10 21:48 UTC, leonardocustodio approved these changes

2022-10-11 22:08 UTC, gabrielokura approved these changes

2022-10-11 22:08 UTC, Lohann approved these changes

2022-10-12 09:10 UTC, merged