Starting point of substrate_metadata
rankanizer/polkadart pull request #75
Opened 2022-10-08 09:52 UTC by justkawal

This is the starting point of this substrate_metadata repo.

It adds:
* Package and its other necessary files.
* Substrate required types and aliases.

2022-10-08 09:54 UTC, justkawal commented
@Lohann, @leonardocustodio needs your review as you guys know alot about substrate and polkadot.

2022-10-10 13:39 UTC, gabrielokura commented on packages/substrate_metadata/lib/old/definitions/substrate/types.dart
> +const types = {
Couldn't this be an interface/class/abstract class?

2022-10-10 13:39 UTC, gabrielokura commented on packages/substrate_metadata/lib/old/definitions/substrate/types_alias.dart
> +final typesAlias = <String, Map<String, String>>{
same as above

2022-10-10 15:29 UTC, justkawal commented on packages/substrate_metadata/lib/old/definitions/substrate/types.dart
> +const types = {
Instead I could rename it as SUBSTRATE_TYPES, and it would be much better.

2022-10-10 15:29 UTC, justkawal commented on packages/substrate_metadata/lib/old/definitions/substrate/types_alias.dart
> +final typesAlias = <String, Map<String, String>>{
Instead renaming it as SUBSTRATE_TYPES_ALIAS, and it would be much better.

2022-10-10 19:07 UTC, justkawal commented on packages/substrate_metadata/lib/old/definitions/substrate/types.dart
> +const types = {
keeping it as normal const is better.

2022-10-10 21:51 UTC, leonardocustodio requested changes
Add the reference where you got the types and we should be good to go

2022-10-10 21:53 UTC, justkawal commented
> Add the reference where you got the types and we should be good to go

Adding references:

`substrateTypes`: https://github.com/subsquid/squid/blob/cc0bc27e16c5c441c39d847be2d560f57afd3b38/substrate-metadata/src/old/definitions/substrate/types.ts#L1

`substrateTypesAlias`: https://github.com/subsquid/squid/blob/cc0bc27e16c5c441c39d847be2d560f57afd3b38/substrate-metadata/src/old/definitions/substrate/typesAlias.ts#L4

2022-10-11 11:59 UTC, leonardocustodio approved these changes

2022-10-11 12:18 UTC, Lohann approved these changes

2022-10-11 12:19 UTC, Lohann commented on packages/substrate_metadata/example/substrate_metadata_example.dart
> +void main() {}
??

2022-10-11 12:19 UTC, Lohann commented on packages/substrate_metadata/pubspec.yaml
> +# TODO: Remove this when polkadart_scale_codec is published
Please create a issue for that and put here, so we remember to publish it in the future

2022-10-11 12:39 UTC, justkawal commented on packages/substrate_metadata/pubspec.yaml
> +# TODO: Remove this when polkadart_scale_codec is published
Now trackable with issue: #83 ( substrate_metadata publish configuration )

2022-10-11 12:39 UTC, justkawal commented on packages/substrate_metadata/example/substrate_metadata_example.dart
> +void main() {}
Removed unused file ✅.

2022-10-11 13:06 UTC, merged