Fix Source Unit Test
rankanizer/polkadart pull request #76
Opened 2022-10-08 20:49 UTC by justkawal

## Any follow ups?
Please review #74, before reviewing this PR.

## Description
* Adds unit-test cases for Source Class.
* Tests Exceptions.
* Tests lowest and highest acceptable value.
* Abbreviations not removed, as it helps to mirror the function calls.

## Why?
* Issue #41

2022-10-10 21:44 UTC, leonardocustodio approved these changes

2022-10-12 12:19 UTC, Lohann commented on packages/polkadart_scale_codec/lib/src/core/source.dart
> +    var len = uncompact();
why the name of this method is `compactLength` when it doesn't return a length? Also it may return an error when the length is greater than dart's `Int` type.

2022-10-12 12:23 UTC, Lohann approved these changes

2022-10-12 12:27 UTC, Lohann requested changes

2022-10-12 12:27 UTC, Lohann commented on packages/polkadart_scale_codec/test/source_test.dart
> +  });
I'm missing a test for `EOFException` here:

`bytes`: returns an `EOFException` when the bytes length doesn't match
`str`: Same case, and also should return an error if the bytes aren't a valid String

2022-10-12 14:34 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/source.dart
> +    var len = uncompact();
Done ✅.
Renamed to `lengthOfCompact`.

2022-10-12 14:35 UTC, justkawal commented on packages/polkadart_scale_codec/test/source_test.dart
> +  });
Added exception test-cases ✅.

2022-10-12 18:28 UTC, Lohann approved these changes

2022-10-12 18:28 UTC, Lohann commented on packages/polkadart_scale_codec/test/source_test.dart
> +  });
**[optional suggestion]**
I don't think this should be an `AssertionException`, instead should be something more granular, like `InvalidStringException`

2022-10-12 18:30 UTC, justkawal commented on packages/polkadart_scale_codec/test/source_test.dart
> +  });
Can be a `InvalidCompactLengthException` as it was predicted to get `int` when an encoded string as hex was passed but found `BigInt` in length.

2022-10-12 18:33 UTC, justkawal commented on packages/polkadart_scale_codec/test/source_test.dart
> +  });
Nice I'll change it right-away.

2022-10-12 18:35 UTC, Lohann commented on packages/polkadart_scale_codec/test/source_test.dart
> +  });
What happens if you provide an invalid ut8-string to this function?
```dart
utf8.decode(buf.toList())
```
Does it returns null? if so, we must have a test case for it.

2022-10-12 22:52 UTC, leonardocustodio commented on packages/polkadart_scale_codec/lib/src/core/source.dart
> +    var len = uncompact();
I don't see how what is the difference of `compactLenght` and `lengthOfCompact`
They mean exactly the same thing.... Between both I would stay with the first option..

2022-10-12 22:55 UTC, leonardocustodio requested changes

2022-10-12 22:55 UTC, leonardocustodio commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    int len = source.lengthOfCompact();
No abbreviations... length not len

2022-10-12 22:55 UTC, leonardocustodio commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    var n = source.uncompact();
Also, have my doubts about `uncompact` do we use similar terms to other types?
Shouldn't it be `decode` maybe?

2022-10-12 22:55 UTC, leonardocustodio commented on packages/polkadart_scale_codec/test/source_test.dart
> +    var computedVal = source.uncompact();
value not val

2022-10-13 07:07 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    var n = source.uncompact();
As far as I know its doing the opposite of compact.
Otherwise, I'll rename it to `decodeCompact`. Does that sound good ?

2022-10-13 07:07 UTC, justkawal commented on packages/polkadart_scale_codec/test/source_test.dart
> +    var computedVal = source.uncompact();
Alright

2022-10-13 07:07 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    int len = source.lengthOfCompact();
Alright

2022-10-14 18:57 UTC, justkawal commented on packages/polkadart_scale_codec/test/source_test.dart
> +  });
Alright, Testing this case scenario.
That's nice to point this thing out.

2022-10-14 19:31 UTC, pastre commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    var n = source.uncompact();
The opposite of `compact` is `expand` or `extract`, although in this context I'd prefer `encode`/`decode` or `zip`/`unzip`

2022-10-15 12:05 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/codec.dart
> +    var n = source.uncompact();
`extract` sounds good. Thanks @pastre

2022-10-16 20:22 UTC, leonardocustodio approved these changes

2022-10-17 06:42 UTC, merged