Test cases for decode Signed and Unsigned integers
rankanizer/polkadart pull request #85
Opened 2022-10-11 14:35 UTC by gabrielokura

## Any follow ups?

Please review #73 before this one.

## Description
Creating unit tests for decoding strings to signed and unsigned integers.

## Why?
Continuation of issue #54 

## How?
1. Update signed int tests with decode test group
2. Update unsigned int tests with decode test group

## Testing Plan 
Run `dart test` on packages/polkadart_scale_codec folder.

2022-10-11 15:15 UTC, gabrielokura commented
I saw your comments on the last PR @pastre. 

I'll update this branch with those comments

2022-10-11 20:27 UTC, justkawal requested changes
Just a few important changes
Others LGTM

2022-10-11 20:27 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/util/functions.dart
> +    throw InvalidSizeException(
Please include `i` here to indicate that the exception was occurred in Signed Comparison.

I think that the below exception message clarifies more about the exception.

'Invalid value at i$bitSize. $value is out of range $min - $max.'

2022-10-11 20:27 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/util/functions.dart
> +        'Invalid value. $value is out of range $min - $max.');
Please include `i` here to indicate that the exception was occurred in Signed Comparison.

I think that the below exception message clarifies more about the exception.

'Invalid value at i$bitSize. $value is out of range $min - $max.'

2022-10-11 20:27 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/util/functions.dart
> +        'Invalid value. $value is out of range 0 - $max.');
Please include `u` here to indicate that the exception was occurred in Signed Comparison.

I think that the below exception message clarifies more about the exception.

'Invalid value at u$bitSize. $value is out of range $min - $max.'

2022-10-11 20:27 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/util/functions.dart
> +        'Invalid value. $value is out of range min - $max.');
Please include `u` here to indicate that the exception was occurred in Signed Comparison.

I think that the below exception message clarifies more about the exception.

'Invalid value at u$bitSize. $value is out of range $min - $max.'

2022-10-11 21:53 UTC, gabrielokura commented on packages/polkadart_scale_codec/lib/src/util/functions.dart
> +    throw InvalidSizeException(
nice

2022-10-11 22:12 UTC, justkawal commented on packages/polkadart_scale_codec/lib/src/core/source.dart
> +      throw UnprocessedDataLeftException();
Nice

2022-10-12 12:14 UTC, Lohann approved these changes
LGTM!

2022-10-14 18:50 UTC, pastre commented on packages/polkadart_scale_codec/lib/src/util/functions.dart
> +bool compare(Comparable value, Comparable min, Comparable max) {
This sort of function is called `clamp`. We could rename it to `isClamped` or `isBetween`. Sorry for providing a bad example in the past comment! 
Another improvement would be to extend `Comparable` so that we get this syntax: `aComparable.isBetween(min, max)`

2022-10-14 18:51 UTC, pastre commented on packages/polkadart_scale_codec/lib/src/util/functions.dart
> +        'Invalid value at i$bitSize. $value is out of range $min - $max.');
A good format for exception message is to provide what is expected to happen and what is actually happening
```suggestion
        'Expected value to be between  $min and $max, but got $value');
```

2022-10-14 18:54 UTC, pastre commented on packages/polkadart_scale_codec/test/test_types/signed_int_test.dart
> +      test('Given an encoded string `0x45` it should return 69', () {
please don't use magic numbers and properly describe the scenario that you're testing
```suggestion
      test('Given an encoded string when it represents a positive integer it should be decoded', () {
```

2022-10-14 18:55 UTC, pastre commented on packages/polkadart_scale_codec/test/test_types/signed_int_test.dart
> +                exception.toString() == expectedErrorMessage),
Testing exception type is enough

2022-10-14 18:55 UTC, pastre commented on packages/polkadart_scale_codec/test/test_types/unsigned_int_test.dart
> +          'Should return correct encoded data when value fits 8 bits and is positive',
nice description!

2022-10-14 18:57 UTC, pastre commented on packages/polkadart_scale_codec/test/test_types/unsigned_int_test.dart
> +      test('Should throw InvalidSizeException when value is greater than 255',
magic numbers again. 
```suggestion
      test('Given an 8 bit decoder when value can't be represented it should throw',
```

2022-10-14 18:59 UTC, pastre commented on packages/polkadart_scale_codec/test/util/functions_test.dart
> +    test('Should return false when an integer value is out of the range', () {
There are two ways to be out of range: upper boundary and lower boundary. We should have two tests

2022-10-14 19:01 UTC, pastre commented on packages/polkadart_scale_codec/test/util/functions_test.dart
> +    test('Should throw TypeError when values have different types', () {
We don't need to test BigInt AND int, they both conform to Comparable and we know that Comparable works. That's the beauty of well-designed abstractions

2022-10-14 19:04 UTC, pastre reviewed
You could've split this in multiple PRs: one that changes the exception, one that fixes comparable, one that updates signed int tests and one that updates unsigned int tests

2022-10-16 19:13 UTC, gabrielokura commented on packages/polkadart_scale_codec/lib/src/util/functions.dart
> +bool compare(Comparable value, Comparable min, Comparable max) {
Create #96 to follow this

2022-10-16 19:17 UTC, gabrielokura commented
Closing this PR because requested changes will be on futures PRs (as #95)

2022-10-16 19:17 UTC, closed without merging