Add xcm schema
rankanizer/polkadart pull request #87
Opened 2022-10-11 20:46 UTC by justkawal

## Any follow ups?
Please review PR: #86 , before reviewing this PR.

## Description
* Adds v0-v2 for xcm.
* Adds `xcm/src.dart` served as and entry point to access xcm schema.

2022-10-12 22:57 UTC, leonardocustodio requested changes
Were those fetched from somewhere? If yes, please put the source

2022-10-16 13:08 UTC, justkawal commented
> Were those fetched from somewhere? If yes, please put the source

Alright, reference added ✅

2022-10-16 13:25 UTC, pastre approved these changes

2022-10-16 20:20 UTC, leonardocustodio approved these changes

2022-10-17 14:12 UTC, leonardocustodio approved these changes

2022-10-18 11:19 UTC, merged