SS58 Codec Implementation.
rankanizer/polkadart pull request #9
Opened 2022-08-25 15:46 UTC by justkawal

- **SS58Codec.decode** and **SS58Codec.encode**
- Test Cases to encode and decode back and forth.
- SS58Codec will provide encode and decode functionality to **ss58**.

2022-08-25 16:43 UTC, leonardocustodio requested changes

2022-08-25 16:43 UTC, leonardocustodio commented on packages/ss58_codec/test/ss58_codec_test.dart
> +    /// basilisk
You only test the happy path.
We should test the exceptions too. Like having an invalid prefix, or the address being the wrong size, etc.

2022-08-25 19:48 UTC, justkawal commented on packages/ss58_codec/test/ss58_codec_test.dart
> +    /// basilisk
Done

2022-08-26 11:22 UTC, leonardocustodio submitted a review, later dismissed

2022-08-26 23:32 UTC, Lohann requested changes

2022-08-26 23:32 UTC, Lohann commented on packages/ss58_codec/lib/src/ss58_codec_base.dart
> +    assert(prefix >= 0 && prefix < 16384, 'invalid prefix');
I don't think we should use assert here, asserts are only verified in `debug` mode, not in `release` mode, more info here:
https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#use-asserts-liberally-to-detect-contract-violations-and-verify-invariants

> assert() allows us to be diligent about correctness without paying a performance penalty in release mode, because Dart only evaluates asserts in debug mode.

Instead, you should create and throw custom Exceptions, example:
https://github.com/flutter/flutter/blob/3.3/packages/flutter_tools/lib/src/build_system/exceptions.dart#L9-L37

2022-08-26 23:32 UTC, Lohann commented on packages/ss58_codec/lib/src/ss58_codec_base.dart
> +  /// Encode SS58 address into canonical string format
This description also should include what exceptions this method throws, and what pre-conditions are verified

2022-08-26 23:32 UTC, Lohann commented on packages/ss58_codec/lib/src/ss58_codec_base.dart
> +List<int> computeHash(Uint8List data, int length) {
Documentation missing for this method

2022-08-26 23:32 UTC, Lohann commented on packages/ss58_codec/lib/src/ss58_codec_base.dart
> +class SS58Codec {
Documentation missing for this class

2022-08-26 23:32 UTC, Lohann commented on packages/ss58_codec/lib/src/ss58_codec_base.dart
> +  static Address decode(String s) {
I think more granular exceptions are needed here too, `invalidAddress` is too generic. 

Example of Exceptions:
https://github.com/paritytech/substrate/blob/polkadot-v0.9.27/primitives/core/src/crypto.rs#L200-L230

Example on how SS58 is decoded in rust:
https://github.com/paritytech/substrate/blob/polkadot-v0.9.27/primitives/core/src/crypto.rs#L262-L304

2022-08-27 08:50 UTC, justkawal commented on packages/ss58_codec/lib/src/ss58_codec_base.dart
> +    assert(prefix >= 0 && prefix < 16384, 'invalid prefix');
Done ✅

2022-08-27 08:51 UTC, justkawal commented on packages/ss58_codec/lib/src/ss58_codec_base.dart
> +List<int> computeHash(Uint8List data, int length) {
Done ✅

2022-08-27 08:51 UTC, justkawal commented on packages/ss58_codec/lib/src/ss58_codec_base.dart
> +class SS58Codec {
Done ✅

2022-08-27 09:30 UTC, justkawal commented on packages/ss58_codec/lib/src/ss58_codec_base.dart
> +  static Address decode(String s) {
Rust Codes are pretty well documented and makes it much easier to understand things now-a-days.

Thanks.

2022-08-27 20:39 UTC, Lohann approved these changes
Approved!

2022-08-27 20:44 UTC, merged